// 10 Morning Variations + 10 Evening Variations for Journal auto-fill demo

export interface MorningVariation {
  mood: string;
  plan: string;
  btcThoughts: string;
  bias: string;
  mktStruct: string;
  mentalTags: string[];
  btcNote: string;
  t3Note: string;
  domNote: string;
  macroNote: string;
  levels: string;
  setups: string;
  emotionScore: number;
  fearGreed: string;
  psychAnswers: { sleepWell: boolean; feelingPressure: boolean; seekingExcitement: boolean; recoveringLosses: boolean };
}

export interface EodVariation {
  hasOpen: boolean;
  trades: { id: number; pair: string; side: string; entry: string; exit: string; size: string; pnl: string; rr: string; notes: string }[];
  actualMove: string;
  dayScore: number;
  wins: string;
  lessons: string;
  mistakes: string;
  solutions: string;
  closing: string;
}

export const MORNING_VARIATIONS: MorningVariation[] = [
  {
    mood: "מרגיש ממוקד ורגוע. ישנתי 7.5 שעות, התעוררתי בזמן ועשיתי שגרת בוקר מלאה — מדיטציה 10 דקות, כוס קפה, וסקירת שוק ראשונית. אין לחץ כלכלי מיוחד, ואני מגיע לשוק עם ראש נקי. המטרה היום היא לחכות לסטאפ ולא לרדוף אחרי מהלכים.",
    plan: "היום אני מתמקד רק ב-2-3 סטאפים איכותיים מקסימום. לא מרבה בטריידים. אני עובד לפי הכלל: אם אין Setup A+ — אין כניסה. ה-Risk מוגבל ל-1R בטרייד בודד ו-2R ליום. אם אני מפסיד 2 טריידים ברצף, אני עוצר ליום. בלי חריגות.",
    btcThoughts: "ביטקוין נמצא באזור בגלות באזור 97K-98K, מתחת ל-MA200 ביומי. לא פריצה אמיתית למעלה בינתיים. עדיין בריינג'. הדומיננס עולה — מה שלוחץ על האלטים. אני מניח שביטקוין ימשיך לדשדש ביום הזה ולכן אני מתמקד באלטים עם מומנטום עצמאי.",
    bias: "Bearish",
    mktStruct: "Distribution",
    mentalTags: ["Focused", "Calm"],
    btcNote: "BTC בריינג' צר 96.8K-98.2K, וולום יורד. דומיננס בעלייה ל-54.3%. אין קטליסט לפריצה. אני מצפה לבריקדאון לכיוון 95K אם 96.8K ישבר בוולום.",
    t3Note: "ETH חלש יותר מ-BTC, נסחר מתחת ל-EMA21 ב-4H. SOL מחזיק טוב יותר עם תמיכה ב-$142. AVAX מראה חולשה עם נרות דובייות.",
    domNote: "דומיננס ביטקוין עלה ב-0.8% ביום האחרון — סימן של 'risk off' בשוק. כשהדומיננס עולה, אלטים בד\"כ מדממים. אני שמרני באלטים היום.",
    macroNote: "פד השאיר ריבית ללא שינוי. DXY יציב ב-104.5. S&P500 עלה 0.3% אתמול. אין דאטה מקרו חשוב היום, אז הקריפטו צפוי להיות בטווח צר. CME Gap פתוח ב-95.2K — שווה לשים לב.",
    levels: "BTC:\n- התנגדות: 98,200 / 99,500 / 100,800\n- תמיכה: 96,800 / 95,500 / 94,200\n\nETH:\n- התנגדות: 3,420 / 3,500\n- תמיכה: 3,280 / 3,150\n\nSOL:\n- התנגדות: 148 / 155\n- תמיכה: 142 / 138",
    setups: "1. SOL — Short Breakdown: אם SOL שובר 142$ עם וולום, שורט לכיוון 138$. SL: 144.5$. RR: 1:2.5\n\n2. ETH — Short Rejection: אם ETH מגיע ל-3,420$ ונדחה עם נר דובי ב-15M, שורט ל-3,280$. SL: 3,460$. RR: 1:3.5\n\n3. AVAX — Short Continuation: AVAX מתחת ל-EMA50 עם מגמה יורדת. כניסה בחזרה ל-$32 עם דחייה, SL: $33.2, TP: $29.5. RR: 1:2",
    emotionScore: 8,
    fearGreed: "Fear",
    psychAnswers: { sleepWell: true, feelingPressure: false, seekingExcitement: false, recoveringLosses: false },
  },
  {
    mood: "קצת עייף — ישנתי רק 5 שעות בגלל שנשארתי ער לצפות בנרות הסגירה של ניו-יורק. מרגיש שאני צריך להיות זהיר היום כי חוסר שינה מוביל אותי להחלטות אימפולסיביות. אני רוצה להגביל את עצמי ל-1 טרייד בלבד.",
    plan: "בגלל מצב העייפות — אני עובד על מצב מינימלי. טרייד אחד בלבד, רק אם זה סטאפ A+. אני מעדיף להפסיד הזדמנות מאשר לעשות טעות. Risk מקסימלי: 0.5R. אם הטרייד הראשון הפסד — סוגר את היום.",
    btcThoughts: "BTC עשה מהלך חזק אתמול ועלה 3.2% מהתחתית. כרגע נמצא ב-pullback בריא ב-4H. אם מחזיק מעל ה-EMA21 ב-4H, יש פוטנציאל להמשך. אבל עייפות = אני צופה ולא פועל אלא אם כן Setup מושלם.",
    bias: "Bullish",
    mktStruct: "Markup",
    mentalTags: ["Tired", "Calm"],
    btcNote: "BTC pullback ל-97.5K אחרי ריצה ל-99.2K. EMA21 ב-4H מחזיק כתמיכה. RSI ב-58 — לא overbought. וולום ב-pullback נמוך — סימן בריא.",
    t3Note: "ETH סוף סוף מראה חוזק יחסי, עלה 4.1% מול 3.2% של BTC. SOL פיגר קצת. MATIC נסחר בוולום גבוה — אולי הכנה לפריצה.",
    domNote: "דומיננס ירד ב-0.3% — אלטים מתחילים לנשום. אם הדומיננס שובר 53.5% למטה, נראה alt season mini.",
    macroNote: "נתוני CPI יוצאים מחר — הרבה סוחרים יחכו בצד. VIX ב-15.8, רגוע יחסית. S&P חזק. סביבה macro תומכת ב-risk-on אבל זהירות לפני CPI.",
    levels: "BTC:\n- Key Support: 97,200 (EMA21-4H)\n- Resistance: 99,200 / 100,500\n- Invalidation: below 96,500\n\nETH:\n- Support: 3,380\n- Target: 3,550",
    setups: "1. BTC — Long Pullback: אם BTC מחזיק 97,200 ומראה נר שורי ב-1H, לונג ל-99,200. SL: 96,500. RR: 1:2.8\n\nזהו — רק סטאפ אחד היום עקב עייפות.",
    emotionScore: 5,
    fearGreed: "Neutral",
    psychAnswers: { sleepWell: false, feelingPressure: false, seekingExcitement: false, recoveringLosses: false },
  },
  {
    mood: "מרגיש מצוין! שלושה ימים רצופים של רווחים ואני מרגיש ביטחון גבוה. אבל — אני צריך להיזהר מביטחון יתר. זה בדיוק הנקודה שבה סוחרים עושים over-trade ומחזירים הכל. אני נצמד לתוכנית.",
    plan: "למרות הביטחון, אני שומר על אותו Risk: 1R לטרייד, 2R ליום. לא מגדיל פוזיציות בגלל שאני ברצף חיובי — זה שגיאה קלאסית. מקסימום 3 טריידים. אם אני מרגיש שאני נכנס מתוך 'אגו' ולא מתוך Setup — עוצר.",
    btcThoughts: "BTC פרץ מעל ה-100K לראשונה בשבועיים. מהלך חזק עם וולום גדול. השאלה: האם זו פריצה אמיתית או bull trap? אני מחכה ל-retest של 100K כתמיכה לפני שאני נכנס ללונג.",
    bias: "Bullish",
    mktStruct: "Markup",
    mentalTags: ["Confident", "Sharp"],
    btcNote: "BTC פרץ 100K בוולום של 85B$ — הגבוה ביותר ב-3 שבועות. RSI ב-72 — overbought אבל במגמות חזקות RSI יכול להישאר שם. MA200 ב-98.5K עכשיו תמיכה.",
    t3Note: "ETH ב-3,600$, חזק. SOL ב-158$ — ATH חודשי. LINK פרץ 18$ עם וולום — מעניין לפולו-אפ.",
    domNote: "דומיננס יציב ב-52.8%. אלטים עולים עם BTC — סימן לשוק בריא. לא alt season עדיין אבל כיוון חיובי.",
    macroNote: "CPI יצא נמוך מהצפוי (3.2% vs 3.4%) — דלק ל-risk-on. שוקי מניות ב-ATH. DXY צנח ל-103.2. סביבה מאוד תומכת בקריפטו.",
    levels: "BTC:\n- New Support: 100,000 (פסיכולוגי + פריצה)\n- Target 1: 103,500\n- Target 2: 106,000\n- Invalidation: סגירה מתחת ל-98,500\n\nSOL:\n- Support: 155\n- Target: 168\n\nLINK:\n- Entry zone: 17.8-18.2\n- Target: 20.5",
    setups: "1. BTC — Long Retest: אם BTC עושה retest ל-100K ומחזיק (נר שורי ב-15M), לונג ל-103,500. SL: 99,200. RR: 1:4.4\n\n2. SOL — Long Continuation: SOL בבריקאאוט מ-155$. Pullback ל-155-156 עם החזקה = לונג ל-168$. SL: 152$. RR: 1:3\n\n3. LINK — Long Breakout Follow-up: LINK פרץ 18$. אם מחזיק מעל 17.8 ב-1H, לונג ל-20.5$. SL: 17.2$. RR: 1:4.5",
    emotionScore: 9,
    fearGreed: "Greed",
    psychAnswers: { sleepWell: true, feelingPressure: false, seekingExcitement: true, recoveringLosses: false },
  },
  {
    mood: "לחוץ ומתוסכל. אתמול הפסדתי 2.3R על טרייד אחד שלא כיבדתי בו את ה-SL. עברתי על הכללים שלי ואני מרגיש את זה. היום אני צריך לאפס — לחזור ליסודות. לשבת על הידיים אם צריך.",
    plan: "יום התאוששות. אם אני נכנס לטרייד בכלל, זה רק ב-0.5R. מקסימום טרייד אחד. העדיפות היום היא לא להרוויח — אלא לא להפסיד. לתרגל משמעת. לכתוב כל מחשבה לפני שאני לוחץ על כפתור.",
    btcThoughts: "BTC ב-pullback אחרי הפריצה של אתמול. הגיוני שיתקן קצת. אני לא צריך לרדוף אחרי מהלכים — בפעם האחרונה שעשיתי את זה הפסדתי. הבוקר אני צופה בלבד.",
    bias: "Neutral",
    mktStruct: "Range",
    mentalTags: ["Impulsive", "Hesitant"],
    btcNote: "BTC ירד 2.1% מ-101K ל-98.8K. וולום ירידה גבוה — לא אידאלי. ייתכן המשך ירידה ל-97.5K. EMA21-4H ב-98.2K.",
    t3Note: "ETH ירד 3.5% — יותר מ-BTC. SOL מחזיק יחסית טוב ב-153$. AVAX ו-MATIC ירדו חזק, 5-6%.",
    domNote: "דומיננס עולה שוב — Risk-off mode. אלטים מדממים יותר מ-BTC. סימן שהשוק מפחד.",
    macroNote: "S&P פתח בירידה של 0.7%. VIX קפץ ל-19.2. דולר מתחזק. סביבה macro לא תומכת — עוד סיבה להיות שמרני.",
    levels: "BTC:\n- Support: 98,200 / 97,500 / 96,000\n- Resistance: 99,500 / 100,800\n\nלא מסתכל על אלטים ספציפיים היום — יום צפייה.",
    setups: "אין סטאפים מתוכננים. יום צפייה בלבד. אם משהו מאוד ברור מופיע ב-BTC בלבד — אכנס ב-0.5R מקסימום.\n\nתרחיש יחיד: BTC מגיע ל-97,500$ עם וולום ירידה יורד + נר reversal ב-1H = לונג ל-99K. SL: 96,800$. RR: 1:2.1",
    emotionScore: 3,
    fearGreed: "Extreme Fear",
    psychAnswers: { sleepWell: false, feelingPressure: true, seekingExcitement: false, recoveringLosses: true },
  },
  {
    mood: "נייטרלי — לא טוב ולא רע. ישנתי סביר, שגרה רגילה. אני מגיע לשוק בלי ציפיות מיוחדות. יום שבו אני פשוט עובד לפי התהליך, מבצע את מה שצריך, ואם אין — אני בסדר עם זה.",
    plan: "תוכנית רגילה: מקסימום 3 טריידים, 1R לכל טרייד. אני מחפש סטאפים בגרפים של 4H ונכנס ב-15M. אם השוק שקט ואין מומנטום — לא כופה. העדיפות: אקזקיושן נקי.",
    btcThoughts: "BTC בריינג' צר כבר 3 ימים ברצף — 97K-99K. וולום יורד כל יום. הבריקאאוט הבא (לכל כיוון) יהיה חזק. אני שם התראות על 99.2K ו-96.8K ומחכה.",
    bias: "Neutral",
    mktStruct: "Range",
    mentalTags: ["Calm", "Focused"],
    btcNote: "BTC ב-consolidation. Bollinger Bands מצטמצמים — סימן לתנודתיות קרובה. וולום ממוצע 24H הנמוך ביותר ב-2 שבועות.",
    t3Note: "ETH מחקה את BTC — ריינג' 3,320-3,420. SOL מעניין עם accumulation ב-$145-148. XRP שקט.",
    domNote: "דומיננס יציב ב-53.1% — לא עושה תנועות חדות. שוק מחכה.",
    macroNote: "יום ללא דאטה מקרו. שווקים סגורים בחלק מאסיה (חג). צפי ליום שקט עם breakout אפשרי בפתיחת ניו-יורק.",
    levels: "BTC:\n- Range High: 99,200\n- Range Low: 96,800\n- Mid-range: 98,000\n- Breakout target up: 101,500\n- Breakdown target: 95,000\n\nSOL:\n- Accumulation zone: 145-148\n- Breakout level: 150",
    setups: "1. BTC — Breakout Long: אם BTC שובר 99,200$ בוולום גבוה (x2 ממוצע), לונג ל-101,500$. SL: 98,300$. RR: 1:2.5\n\n2. BTC — Breakdown Short: אם BTC שובר 96,800$ בוולום, שורט ל-95,000$. SL: 97,500$. RR: 1:2.6\n\n3. SOL — Accumulation Breakout: SOL שובר 150$ ומחזיק = לונג ל-158$. SL: 147$. RR: 1:2.7",
    emotionScore: 6,
    fearGreed: "Neutral",
    psychAnswers: { sleepWell: true, feelingPressure: false, seekingExcitement: false, recoveringLosses: false },
  },
  {
    mood: "מרגיש חד ואנרגטי. אימון בוקר, אכילה נקייה, ו-8 שעות שינה. אתמול לא סחרתי — יום חופש מתוכנן. אני חוזר לשוק רענן ועם אנרגיה גבוהה. מוכן לפעול.",
    plan: "יום Full-Power: עד 4 טריידים, 1R לכל אחד. אני מחפש סטאפים בכל הטיימפריימים. היום יש לי את ה-bandwidth המנטלי לנהל מספר פוזיציות במקביל. אבל — כל כניסה חייבת להיות מתוכננת מראש.",
    btcThoughts: "BTC עשה breakout מהריינג' של 3 ימים! פרץ 99.2K בוולום ענק. עכשיו ב-100.8K. המגמה שורית ברורה ב-4H וביומי. אני מחפש לונגים ב-pullbacks.",
    bias: "Bullish",
    mktStruct: "Markup",
    mentalTags: ["Sharp", "Confident", "Focused"],
    btcNote: "BTC breakout מ-99.2K בוולום של 92B$. כרגע 100.8K. המומנטום חזק — MACD crossover ב-4H. RSI ב-68 — חזק אבל לא overbought.",
    t3Note: "ETH פרץ 3,420 — כרגע 3,510. SOL פרץ 150 — כרגע 154. שוק שורי רחב. DOGE עלה 8% — retail entering.",
    domNote: "דומיננס ירד ל-52.4% — הכסף זורם לאלטים. Alt season flags מתחילים להידלק.",
    macroNote: "S&P חדש ATH. NASDAQ +1.2%. DXY שובר 103 למטה. זהב ATH. סביבה risk-on מלאה — רוח גבית חזקה לקריפטו.",
    levels: "BTC:\n- New Support: 100,000 / 99,200\n- Targets: 102,500 / 104,000 / 106,500\n- Invalidation: below 98,500\n\nETH:\n- Support: 3,420 (breakout level)\n- Target: 3,680\n\nSOL:\n- Support: 150\n- Targets: 160 / 168",
    setups: "1. BTC Long Pullback: Pullback ל-100K-100.2K עם bounce = לונג ל-103K. SL: 99,200. RR: 1:3.5\n\n2. ETH Long: Pullback ל-3,450 + bounce = לונג ל-3,680. SL: 3,380. RR: 1:3.3\n\n3. SOL Long: Pullback ל-151-152 + bounce = לונג ל-162. SL: 148. RR: 1:3.3\n\n4. LINK Long: LINK ב-18.5$ עם מומנטום. Entry: pullback ל-18$, SL: 17.2$, TP: 21$. RR: 1:3.75",
    emotionScore: 9,
    fearGreed: "Greed",
    psychAnswers: { sleepWell: true, feelingPressure: false, seekingExcitement: false, recoveringLosses: false },
  },
  {
    mood: "מודאג קצת — יש לי חשבון חשמל גדול לשלם השבוע ואני מרגיש לחץ כלכלי. אני יודע שזה בדיוק הסוג של לחץ שגורם לי לקחת סיכונים מיותרים. אני צריך להפריד: המסחר הוא לא הפתרון ללחץ הפיננסי הזה.",
    plan: "יום Risk-Off. מסחר רק בסימולטור או סקירה תיאורטית. אם אני בכל זאת נכנס — 0.25R מקסימום. לא יותר מטרייד אחד. העדיפות: לשמור על ההון ועל הראש.",
    btcThoughts: "BTC נראה שורי אבל אני לא במצב מנטלי לסחור. לא משנה מה BTC עושה — אני צופה. אם יש Setup מושלם אני מתעד אותו ליומן בלי להיכנס.",
    bias: "Bullish",
    mktStruct: "Markup",
    mentalTags: ["Hesitant", "Tired"],
    btcNote: "BTC ממשיך לטפס — 101.5K. המגמה שורית. אבל אני לא הולך לרדוף. אני מתעד את מה שאני רואה לצורך למידה.",
    t3Note: "ETH חזק — 3,580. SOL ב-157. MATIC עלה 12% — תנועה מעניינת לצפייה.",
    domNote: "דומיננס ב-52.1% — מגמת ירידה. אלטים חזקים.",
    macroNote: "שווקים חיוביים. נתוני תעסוקה חזקים. סביבה תומכת — אבל אני לא בפוזיציה לנצל.",
    levels: "BTC:\n- Support: 100,500 / 99,200\n- Resistance: 103,000 / 105,000\n\nתיעוד בלבד — לא תכנון כניסות.",
    setups: "📌 יום צפייה בלבד — תיעוד סטאפים תיאורטיים:\n\n1. BTC Long Pullback: אם BTC חוזר ל-100.5K, זה Setup A+. לונג ל-103K. SL: 99,500. RR: 1:3.3\n(לא מבוצע — לחץ מנטלי)\n\n2. MATIC: לעקוב אחרי הפריצה — האם 1.05$ מחזיק?\n(לא מבוצע — יום צפייה)",
    emotionScore: 3,
    fearGreed: "Fear",
    psychAnswers: { sleepWell: true, feelingPressure: true, seekingExcitement: false, recoveringLosses: true },
  },
  {
    mood: "יום שישי — מרגיש מוטיבציה גבוהה לסיים את השבוע בנימה חיובית. אני ב-+3.7R השבוע, שזה מצוין. אני לא רוצה להחזיר רווחים. היום — שמרני ומבוקר. אם אני מסיים את השבוע בירוק, זה ניצחון.",
    plan: "יום שישי = יום סגירה. מקסימום 2 טריידים קצרים. Risk מוגבל ל-0.5R לטרייד ו-1R ליום. אני רוצה לשמור על הרווח השבועי. אחרי הצהריים — סקירה שבועית ותכנון לשבוע הבא.",
    btcThoughts: "BTC יציב ב-99K. שוק שקט ליום שישי — כרגיל. הוולום יורד אחרי הצהריים. אני מצפה ליום שקט ומחפש רק scalps קצרים אם בכלל.",
    bias: "Neutral",
    mktStruct: "Range",
    mentalTags: ["Calm", "Confident"],
    btcNote: "BTC בריינג' 98.5-99.5K. וולום נמוך כצפוי ליום שישי. אין קטליסט. CME סוגר היום — ייתכן gap בשבת.",
    t3Note: "ETH ב-3,380 — שקט. SOL ב-148. שוק בהמתנה לסוף שבוע.",
    domNote: "דומיננס יציב ב-53%. לא תנועות חדות.",
    macroNote: "יום שישי — ליקווידיטי נמוך. S&P סוגר מוקדם. אירופה כבר סגרה. אסיה ישנה. יום קלאסי של thin orderbook.",
    levels: "BTC:\n- Range: 98,500 - 99,500\n- Scalp Long zone: 98,500-98,700\n- Scalp Short zone: 99,300-99,500",
    setups: "1. BTC Range Scalp Long: Touch ב-98,500 עם bounce = לונג ל-99,200. SL: 98,200. RR: 1:2.3. גודל: 0.5R\n\n2. BTC Range Scalp Short: Touch ב-99,500 עם rejection = שורט ל-98,700. SL: 99,800. RR: 1:2.7. גודל: 0.5R",
    emotionScore: 7,
    fearGreed: "Neutral",
    psychAnswers: { sleepWell: true, feelingPressure: false, seekingExcitement: false, recoveringLosses: false },
  },
  {
    mood: "מרגיש לחוץ — אני ברצף של 4 הפסדים ו-3.8R- השבוע. זה כואב אבל אני צריך לעצור ולנשום. ישבתי שעה על תחקיר וזיהיתי שהבעיה היא over-trading: אני נכנס ליותר מדי טריידים מתוך רצון לפצות.",
    plan: "תוכנית 'חירום': מקסימום טרייד אחד בלבד. גודל: 0.5R. רק Setup A+ עם RR של 1:3 מינימום. אם אני מרגיש את הדחף להיכנס מתוך כעס — אני עוצר ויוצא להליכה של 10 דקות.",
    btcThoughts: "BTC ירד 5% בשבוע. השוק דובי ואני כבר הפסדתי שלושה שורטים כי נכנסתי מאוחר מדי אחרי התנועה. הלקח: לחכות ל-bounce ולהיכנס בזול, לא לרדוף.",
    bias: "Bearish",
    mktStruct: "Markdown",
    mentalTags: ["Impulsive", "Hesitant", "Tired"],
    btcNote: "BTC ב-94.5K — שבר את ה-96K. כרגע oversold ב-RSI (28). צפוי dead cat bounce ל-95.5-96K לפני המשך ירידה.",
    t3Note: "ETH ב-3,020 — חלש מאוד. SOL ב-128 — שבר תמיכות. שוק אדום עמוק.",
    domNote: "דומיננס קפץ ל-55.2% — capital flight מאלטים ל-BTC. סימן של panic selling באלטים.",
    macroNote: "Fed hawkish. DXY ב-106. S&P ירד 2.1% בשבוע. סביבה macro רעילה. ניתוח: להמתין לירידה ל-yield curves.",
    levels: "BTC:\n- Support: 94,000 / 92,500 / 90,000\n- Resistance: 95,500 / 96,000 / 97,500\n- Dead cat bounce zone: 95,500-96,000",
    setups: "1. BTC — Short Bounce: אם BTC עולה ל-95,500-96,000 ונדחה (נר דובי ב-1H), שורט ל-93,000. SL: 96,800. RR: 1:3.1. גודל: 0.5R\n\n(טרייד יחיד — אסור יותר מזה)",
    emotionScore: 2,
    fearGreed: "Extreme Fear",
    psychAnswers: { sleepWell: false, feelingPressure: true, seekingExcitement: false, recoveringLosses: true },
  },
  {
    mood: "מוטיבציה מחודשת! לקחתי שבוע חופשה מהמסחר ועשיתי detox מלא. לא הסתכלתי על גרפים, לא קראתי חדשות. חזרתי עם ראש צלול לחלוטין. מרגיש כאילו מתחיל מחדש — וזה מדהים.",
    plan: "יום חזרה רך: מקסימום 2 טריידים, 0.75R לכל אחד. היום בעיקר לימוד מחדש של המצב בשוק. סקירה מעמיקה של מה קרה בשבוע שעבר, זיהוי רמות חדשות, הבנת הסנטימנט.",
    btcThoughts: "BTC עלה 8% בזמן שלא הייתי. כרגע ב-103K. אני צריך לסקור מה קרה — אילו רמות נשברו, מה ה-context החדש. לא נכנס לטריידים עד שאני מרגיש שאני מבין את השוק.",
    bias: "Bullish",
    mktStruct: "Markup",
    mentalTags: ["Calm", "Focused", "Confident"],
    btcNote: "BTC ב-103K — ATH חדש! כנראה פרץ 100K בזמן שלא הייתי. MA200 ב-97K — רחוק. מגמה שורית חזקה ביומי ובשבועי.",
    t3Note: "ETH ב-3,750 — ATH חודשי. SOL ב-168 — חזק מאוד. AVAX ב-42$ — עלייה של 18% בשבוע.",
    domNote: "דומיננס ב-51.5% — הנמוך ביותר ב-חודש. Alt season mode עם כמה אלטים שעולים 20-40%.",
    macroNote: "Fed signals של הורדת ריבית בספטמבר. DXY ירד ל-102. שוקי מניות ATH. זהב ATH. סביבה מושלמת ל-risk-on.",
    levels: "BTC:\n- Support: 102,000 / 100,500\n- Target: 105,000 / 108,000\n\nETH:\n- Support: 3,650\n- Target: 4,000\n\nSOL:\n- Support: 163\n- Target: 180",
    setups: "1. BTC Long: Pullback ל-102K + bounce ב-15M = לונג ל-105K. SL: 101K. RR: 1:3. גודל: 0.75R\n\n2. ETH Long: Pullback ל-3,680 + bounce = לונג ל-3,950. SL: 3,600. RR: 1:3.4. גודל: 0.75R\n\n(שני טריידים מקסימום — יום חזרה)",
    emotionScore: 8,
    fearGreed: "Greed",
    psychAnswers: { sleepWell: true, feelingPressure: false, seekingExcitement: false, recoveringLosses: false },
  },
];

export const EOD_VARIATIONS: EodVariation[] = [
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'BTCUSDT', side: 'LONG', entry: '100200', exit: '103100', size: '0.15', pnl: '435', rr: '2.8', notes: 'Retest של 100K עם נר שורי ב-15M. כניסה מדויקת על ה-EMA21. ניהול מצוין — הזזתי SL ל-breakeven ב-1R רווח ונתתי לרוץ.' },
      { id: 2, pair: 'SOLUSDT', side: 'LONG', entry: '151.5', exit: '148.2', size: '50', pnl: '-165', rr: '-0.7', notes: 'Breakdown מ-150$ — כניסה הייתה בסדר אבל SOL לא הגיב כמצופה. SL הוזז נמוך מדי, צריך היה לצאת מוקדם יותר.' },
    ],
    actualMove: "BTC עשה בדיוק את ה-retest שתכננתי על 100K ואז עלה ל-103.1K. הניתוח של הבוקר היה מדויק ב-BTC. SOL, לעומת זאת, עשה את ההפך — שבר את 150$ למטה ולא החזיק. הטעות שלי ב-SOL: לא שמתי לב שהוולום בפריצה היה חלש.",
    dayScore: 7,
    wins: "1. ביצוע מצוין ב-BTC — כניסה על הרמה המדויקת שתכננתי בבוקר.\n2. ניהול סיכונים נכון — הזזתי SL ל-breakeven ונתתי ל-BTC לרוץ.\n3. לא נכנסתי לטרייד שלישי למרות שהתפתה — שמירה על משמעת.",
    lessons: "1. וולום בפריצה חשוב — SOL פרץ 150$ בלי וולום ולכן נכשל. בפעם הבאה אני מוודא וולום x2 ממוצע.\n2. צריך לנתח כל נכס בנפרד — לא להניח ש'אם BTC עולה, גם SOL יעלה'.\n3. SL management — ב-SOL הייתי צריך SL הדוק יותר. 3$ SL על פוזיציה של 50 SOL זה 150$, שזה 0.7R. בסדר אבל יכולתי להגביל ל-0.5R.",
    mistakes: "1. כניסה ל-SOL לפני אישור וולום — נכנסתי על סמך מחיר בלבד בלי לבדוק OBV.\n2. לא בדקתי correlation: SOL ו-BTC לא זזו יחד היום, ואני התעלמתי מזה.\n3. הזזת SL ב-SOL — הרחבתי את ה-SL מ-149$ ל-148$ בגלל FOMO. זה הוסיף 0.2R לחשיפה.",
    solutions: "1. חוק חדש: לא נכנס לפריצה בלי וולום x2 ממוצע. מוסיף את זה לצ'קליסט.\n2. בודק correlation בין BTC ל-ALT לפני כניסה — אם BTC שורי ו-ALT לא עוקב, זה red flag.\n3. SL לא מוזז לרעה — NEVER. מוסיף reminder בולט בצ'קליסט.",
    closing: "יום חיובי בסה\"כ. +270$ (נטו). ה-BTC trade היה מצוין ומראה שהתוכנית עובדת כשאני עוקב אחריה. ה-SOL trade היה שגיאה שאני יכול ללמוד ממנה. המפתח: וולום ו-correlation. מחר ממשיכים.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'ETHUSDT', side: 'SHORT', entry: '3420', exit: '3285', size: '2', pnl: '270', rr: '3.4', notes: 'Rejection מ-3,420$ בדיוק כמו בתוכנית. נר דובי ענק ב-15M עם וולום. שורט מושלם. יצאתי ב-TP.' },
      { id: 2, pair: 'AVAXUSDT', side: 'SHORT', entry: '32.1', exit: '30.2', size: '100', pnl: '190', rr: '1.9', notes: 'Short continuation כמתוכנן. AVAX המשיך את המגמה. יצאתי קצת מוקדם — TP היה ב-29.5$ אבל רציתי לנעול רווח.' },
      { id: 3, pair: 'BTCUSDT', side: 'SHORT', entry: '97800', exit: '97900', size: '0.1', pnl: '-10', rr: '-0.1', notes: 'ניסיון שורט שלא עבד — BTC לא הגיב לרמה. יצאתי מהר עם הפסד מינימלי. אקזקיושן טוב של cut loss.' },
    ],
    actualMove: "השוק עשה בדיוק את מה שציפיתי — ירידות בינוניות. ETH הגיב מושלם לרמת ההתנגדות 3,420$ ועשה ירידה חזקה. AVAX המשיך downtrend. BTC היה היחיד שלא הלך לפי התוכנית — החזיק חזק מדי.",
    dayScore: 9,
    wins: "1. 2 מתוך 3 טריידים רווחיים — win rate של 66%.\n2. RR ממוצע מצוין — 3.4R ב-ETH!\n3. Cut loss מהיר ב-BTC — הפסד של 0.1R בלבד. זו משמעת.\n4. סה\"כ +450$ — יום מצוין.\n5. הניתוח של הבוקר היה מדויק ב-2 מתוך 3 נכסים.",
    lessons: "1. כשהניתוח מדויק והאקזקיושן נקי — התוצאות באות. אין קסם, רק תהליך.\n2. לצאת מוקדם מ-TP זה OK אם הסיבה היא ניהול סיכונים (AVAX).\n3. BTC לא תמיד הולך עם הכיוון הכללי — צריך לתת לו יותר כבוד כנכס עצמאי.",
    mistakes: "1. ב-AVAX יצאתי ב-30.2$ במקום 29.5$ — הפסדתי 130$ פוטנציאליים. אבל זה היה החלטה מודעת.\n2. כניסה ל-BTC הייתה קצת 'בגלל שאני כבר ב-flow' — לא סטאפ A+.",
    solutions: "1. אם יוצאים מוקדם מ-TP — לתעד את הסיבה ולבדוק בדיעבד אם ההחלטה הייתה נכונה.\n2. לא להיכנס לטרייד רק כי 'אני כבר ברול' — כל כניסה חייבת לעמוד בסטנדרט A+ באופן עצמאי.",
    closing: "אחד הימים הטובים שלי! הניתוח היה מדויק, האקזקיושן נקי, וה-risk management היה ברמה גבוהה. +450$ ו-2 מתוך 3 wins. זה מה שקורה כשאני עוקב אחרי התוכנית. ממשיכים ככה.",
  },
  {
    hasOpen: false,
    trades: [],
    actualMove: "השוק היה שקט מאוד — BTC זז 0.4% כל היום. לא היה אף סטאפ שעמד בקריטריונים שלי. עדיף יום ללא טריידים מאשר טריידים בכוח. 'הטרייד הטוב ביותר הוא לפעמים אי-כניסה.'",
    dayScore: 7,
    wins: "1. לא סחרתי למרות שרציתי — זו משמעת.\n2. ניצלתי את הזמן לסקירה מעמיקה של 3 נכסים חדשים שלא מכיר.\n3. שמרתי על ההון — 0$ הפסד = ניצחון ביום שקט.",
    lessons: "1. לא כל יום הוא יום מסחר. ימים שקטים = ימי למידה.\n2. FOMO על חוסר פעולה הוא אמיתי — אני מרגיש 'חסר' כשלא סוחר. צריך לעבוד על זה.\n3. 'אם אתה לא יודע מה לעשות — אל תעשה כלום.' — חוק ברזל.",
    mistakes: "1. כמעט נכנסתי לטרייד ב-BTC בלי Setup ברור — רק מתוך שעמום. נעצרתי ברגע האחרון.\n2. ביליתי 2 שעות מול המסך בלי תכלית — צריך להגדיר זמנים קשיחים לצפייה.",
    solutions: "1. הגדרת זמני צפייה: 09:00-10:30 ו-15:00-17:00. אם אין Setup עד 17:00 — סוגר.\n2. בימים שקטים — ללמוד נכס חדש או לעשות backtest במקום לשבת מול הגרף.",
    closing: "יום ללא טריידים. 0$ P&L. אבל 100% משמעת ולמידה. אני גאה שלא נפלתי ל-FOMO. השוק יהיה פה מחר.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'BTCUSDT', side: 'LONG', entry: '95800', exit: '94200', size: '0.2', pnl: '-320', rr: '-1.3', notes: "נכנסתי ללונג על 'תמיכה' שנשברה. לא כיבדתי את ה-SL הראשוני ב-95,200 — הזזתי אותו ל-94,800 ואז ל-94,200. שגיאה חמורה." },
      { id: 2, pair: 'ETHUSDT', side: 'LONG', entry: '3150', exit: '3080', size: '3', pnl: '-210', rr: '-0.9', notes: 'REVENGE TRADE. נכנסתי מיד אחרי ההפסד ב-BTC כי רציתי להחזיר. ETH גם ירד. ידעתי שזו טעות אבל נכנסתי בכל זאת.' },
    ],
    actualMove: "השוק ירד חזק — BTC שבר 96K ועשה flush ל-93.8K. הניתוח שלי של הבוקר היה Neutral/Range אבל הגרף אמר Bearish. התעלמתי מהסימנים כי רציתי לונג. זה כישלון של ego — רציתי להיות צודק במקום להרוויח.",
    dayScore: 2,
    wins: "1. אין ניצחונות ממשיים היום.\n2. דבר אחד חיובי — סוף סוף עצרתי אחרי 2 הפסדים ולא המשכתי לטרייד שלישי.",
    lessons: "1. REVENGE TRADING הוא ההרס הגדול ביותר שלי. כל פעם שאני מפסיד ומיד נכנס — אני מפסיד שוב.\n2. הזזת SL = הפרת חוזה עם עצמי. זה לא ניהול — זה HOPE TRADING.\n3. צריך cooling period — 30 דקות מינימום בין טריידים, ו-60 דקות אחרי הפסד.",
    mistakes: "1. הזזת SL ב-BTC מ-95,200 ל-94,200 — הגדלתי את ההפסד ב-60%.\n2. Revenge Trade ב-ETH — נכנסתי תוך 3 דקות מההפסד. לא חשבתי, רק הגבתי.\n3. סחרתי נגד המגמה — השוק היה דובי ואני ניסיתי לתפוס תחתית.\n4. לא כיבדתי את תוכנית הבוקר — כתבתי Neutral ואז סחרתי Bullish.",
    solutions: "1. SL הוא קו אדום — NEVER move it against me. מדביק פתק על המסך.\n2. חוק חדש: 30 דקות cooling period אחרי כל טרייד. 60 דקות אחרי הפסד.\n3. אם הביאס Neutral — לא נכנס ללונגים ארוכים. רק scalps עם SL הדוק.\n4. journaling בזמן אמת: לפני כל כניסה — כותב את הסיבה. אם אני לא יכול לנמק = לא נכנס.",
    closing: "יום קשה. -530$. -2.2R. עברתי על כל כלל שיש לי. אני כותב את זה כי חשוב לתעד את הכישלונות. הלקח העיקרי: SL קדוש, cooling period חובה, ו-revenge trading = אויב מספר 1. מחר יום חדש.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'LINKUSDT', side: 'LONG', entry: '17.85', exit: '20.10', size: '200', pnl: '450', rr: '3.5', notes: 'Breakout follow-up מ-18$. כניסה על pullback ל-17.85 עם bounce מדויק. נתתי לו לרוץ ויצאתי ב-20.1. מושלם.' },
    ],
    actualMove: "יום עם טרייד אחד בלבד — אבל מה טרייד! LINK עשה את הבריקאאוט שציפיתי ורץ 12.6%. הכניסה הייתה מדויקת על ה-pullback. הסבלנות השתלמה — חיכיתי 4 שעות לסטאפ הנכון.",
    dayScore: 10,
    wins: "1. טרייד מושלם — כניסה מדויקת, SL לוגי, TP הושג.\n2. סבלנות — חיכיתי 4 שעות ולא נכנסתי לטריידים אחרים.\n3. +450$ מטרייד אחד. +3.5R. זו עקביות.\n4. תוכנית הבוקר בוצעה ל-100%.",
    lessons: "1. טרייד אחד טוב שווה יותר מ-5 טריידים בינוניים.\n2. סבלנות היא ה-edge האמיתי — לא ניתוח טכני.\n3. כשיש לך סטאפ A+ ואתה מבצע נקי — התוצאות מדברות.",
    mistakes: "1. אין טעויות היום — אבל יש נקודה לשיפור: הייתי יכול לצאת ב-20.5$ אם הייתי מחזיק עוד 20 דקות. Trail stop יותר רחב בפעם הבאה?\n2. קצת FOMO על SOL שגם עלה 5% — אבל לא נכנסתי כי לא היה בתוכנית.",
    solutions: "1. לשקול trailing stop של 1.5% במקום 1% על breakout trades — נותן יותר מרחב.\n2. להמשיך עם הגישה של quality over quantity — זה עובד.",
    closing: "יום מופתי. +450$, +3.5R, 100% win rate, 100% execution. זה מה שקורה כשסבלנות + תוכנית + משמעת מתחברים. LINK היה הטרייד של השבוע.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'BTCUSDT', side: 'SHORT', entry: '99400', exit: '98800', size: '0.1', pnl: '60', rr: '0.8', notes: "Scalp שורט מראש הריינג׳. כניסה ויציאה מהירות. RR לא אידאלי אבל רווח נקי." },
      { id: 2, pair: 'BTCUSDT', side: 'LONG', entry: '98600', exit: '99100', size: '0.1', pnl: '50', rr: '0.7', notes: "Scalp לונג מתחתית הריינג׳. שוב — RR לא מושלם אבל הלוגיקה הייתה נכונה." },
    ],
    actualMove: "BTC נע בטווח צר בדיוק כמו שציפיתי. הצלחתי לסקאלפ פעמיים — שורט מלמעלה ולונג מלמטה. לא RR גבוה אבל consistent. יום שישי קלאסי עם thin orderbook.",
    dayScore: 6,
    wins: "1. 2/2 wins — 100% win rate.\n2. ניתוח מדויק — Range play עבד.\n3. שמרתי על 0.5R מקסימום כמתוכנן.\n4. סיימתי את השבוע בירוק.",
    lessons: "1. Range trading ביום שישי זה אסטרטגיה לגיטימית אם הריינג' ברור.\n2. RR נמוך (0.7-0.8R) מקובל ב-scalps אם ה-win rate גבוה.\n3. חשוב לדעת מתי לעצור — 2 scalps ודי.",
    mistakes: "1. RR לא אופטימלי — הייתי יכול לחכות ל-entries יותר מדויקות עם SL יותר הדוק.\n2. סיכון מצטבר: 2 טריידים של 0.5R = 1R חשיפה. זה על הגבול של מה שתכננתי.",
    solutions: "1. ב-scalps — להגדיר SL הדוק יותר (0.3R) כדי לאפשר יותר ניסיונות.\n2. לתעד scalp strategy בנפרד — כללים אחרים מ-swing.",
    closing: "יום שישי סולידי. +110$. +1.5R. שמרתי על הרווח השבועי. סיכום שבועי: +4.8R. שבוע מצוין. עכשיו מנוחה ותכנון לשבוע הבא.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'ONDOUSDT', side: 'LONG', entry: '1.42', exit: '1.68', size: '500', pnl: '130', rr: '2.2', notes: 'ONDO breakout מ-1.40. כניסה ב-pullback ל-1.42 עם SL ב-1.30. Target ב-1.70 — יצאתי קצת מוקדם ב-1.68 כי ראיתי חולשה.' },
      { id: 2, pair: 'OPUSDT', side: 'LONG', entry: '2.85', exit: '2.78', size: '200', pnl: '-14', rr: '-0.2', notes: 'OP לא הצליח לפרוץ. יצאתי מהר עם הפסד קטן. אקזקיושן טוב של cut loss.' },
      { id: 3, pair: 'ATOMUSDT', side: 'SHORT', entry: '9.50', exit: '9.20', size: '100', pnl: '30', rr: '1.0', notes: 'ATOM short על rejection מ-EMA50. תנועה קטנה אבל מדויקת.' },
    ],
    actualMove: "יום עם 3 טריידים — 2 רווחיים ו-1 הפסד קטן. ONDO היה הכוכב — breakout מושלם. OP לא עבד אבל יצאתי מהר. ATOM trade היה bonus שלא תכננתי אבל ראיתי Setup ברור.",
    dayScore: 8,
    wins: "1. ONDO trade — כניסה מדויקת, RR של 2.2.\n2. Cut loss מהיר ב-OP — רק 0.2R.\n3. ATOM bonus trade — ראיתי הזדמנות וביצעתי נקי.\n4. סה\"כ +146$ נטו.",
    lessons: "1. Alt coins עם momentum עצמאי (כמו ONDO) הם הזדמנויות מצוינות.\n2. Cut loss מהיר שומר על הון ועל פסיכולוגיה — לא כואב כשזה -0.2R.\n3. להיות גמיש — ATOM לא היה בתוכנית אבל Setup ברור = כניסה.",
    mistakes: "1. ONDO — יצאתי ב-1.68 במקום 1.70 (TP). הפסדתי 10$ מיותרים מנטריקות.\n2. OP — הכניסה הייתה קצת מוקדמת. הייתי צריך לחכות לפריצה ברורה של 2.90.",
    solutions: "1. Trust the TP — אם הגעתי ל-1.68, עוד 0.02$ לא שווים לסגור מוקדם.\n2. באלטים קטנים — לחכות לפריצה ברורה עם וולום, לא breakout attempt.",
    closing: "יום טוב עם mix של trades. +146$. מנהל את אלטים יותר ויותר טוב. ה-watchlist המורחב עובד — ONDO היה discovery מצוין.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'BTCUSDT', side: 'LONG', entry: '97500', exit: '99200', size: '0.2', pnl: '340', rr: '2.4', notes: 'Dead cat bounce trade מ-97,500 כמתוכנן בדיוק. נכנסתי על reversal candle ב-1H. SL ב-96,800. TP ב-99,200. Perfect execution.' },
    ],
    actualMove: "BTC עשה את ה-bounce מ-97,500 כפי שתכננתי. מרשים כי הניתוח היה שהשוק דובי אבל oversold — וזה בדיוק מה שקרה. הטרייד הזה הוכיח שאפשר להרוויח גם בשוק דובי עם Entry נכון.",
    dayScore: 8,
    wins: "1. ניתוח מדויק של bounce zone.\n2. ביצוע מושלם — כניסה, ניהול, יציאה.\n3. +340$ מטרייד אחד.\n4. עקביות עם תוכנית הבוקר למרות שהיום היה מנטלית קשה.",
    lessons: "1. אפשר להרוויח בכל שוק — הכיוון לא משנה, Entry נכון משנה.\n2. Oversold ≠ Buy. Oversold + reversal signal + key level = Buy.\n3. יום recovery מוצלח — אחרי 4 הפסדים, טרייד אחד נקי של 2.4R מחזיר ביטחון.",
    mistakes: "1. הייתי יכול להחזיק עד 99,500 (BTC המשיך לעלות אחרי היציאה שלי). אבל — TP הושג, אז זו לא טעות, רק missed opportunity.\n2. ביום כזה רגשי, הייתי צריך לכתוב בדף לפני הכניסה — עשיתי את זה בראש.",
    solutions: "1. לשקול partial exit: 70% ב-TP1, 30% trail — במיוחד על bounce trades שיכולים לרוץ.\n2. journaling לפני כל כניסה — גם בימים קשים. במיוחד בימים קשים.",
    closing: "יום recovery מדהים. +340$, +2.4R. מהפסד של 3.8R- בשבוע, חזרתי ל-1.4R-. עוד יום-יומיים טובים ואני חוזר לירוק. הלקח: לא לוותר, אבל גם לא לרדוף.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'SOLUSDT', side: 'LONG', entry: '163', exit: '172', size: '30', pnl: '270', rr: '3.0', notes: 'SOL breakout מ-163$ עם וולום ענק. Pullback ל-163 + bounce. Perfect setup A+. נתתי לו לרוץ ל-172.' },
      { id: 2, pair: 'ETHUSDT', side: 'LONG', entry: '3680', exit: '3820', size: '1.5', pnl: '210', rr: '1.8', notes: 'ETH pullback ל-3,680 כמתוכנן. כניסה על EMA21 ב-1H. RR לא מושלם כי יצאתי מוקדם.' },
    ],
    actualMove: "שוק שורי חזק — BTC ב-ATH, אלטים עפים. SOL עשה 5.5% ו-ETH 3.8%. הניתוח היה מדויק. שני הטריידים עבדו. Alt season mode — ואני מנצל את זה נכון.",
    dayScore: 9,
    wins: "1. 2/2 wins — 100% win rate.\n2. +480$ ביום. +4.8R שבועי (עם היום הזה).\n3. SOL trade — A+ execution.\n4. הניתוח של הבוקר היה מדויק ב-100%.\n5. ניהלתי 2 פוזיציות במקביל בלי לחץ.",
    lessons: "1. בשוק שורי חזק — להישאר Long. לא לחפש שורטים נגד המגמה.\n2. Alt season = הזדמנות זהב. צריך להכין watchlist מראש ולהיות מוכן.\n3. Multiple positions אפשריים כשאני מנוח ומרוכז.",
    mistakes: "1. ETH — יצאתי מוקדם ב-3,820 במקום TP של 3,950. הפסדתי ~195$ פוטנציאליים.\n2. לא נכנסתי ל-LINK למרות שהיה Setup — הייתי עסוק ב-ETH ו-SOL.",
    solutions: "1. Partial exits: במקום לסגור 100% ב-TP1, לסגור 60% ולהשאיר 40% עם trail.\n2. אם יש bandwidth — להכין orders מראש על כל סטאפ כדי לא לפספס.",
    closing: "יום של gold! +480$. שני טריידים מושלמים. Alt season in full effect ואני רוכב על הגל. שבוע סיום: +7.2R. מצוין! סוף שבוע של מנוחה מגיע.",
  },
  {
    hasOpen: true,
    trades: [
      { id: 1, pair: 'BTCUSDT', side: 'LONG', entry: '102200', exit: '102800', size: '0.15', pnl: '90', rr: '0.8', notes: 'Pullback trade — כניסה ב-102K, יצאתי מוקדם כי ראיתי resistance ב-103K. RR לא אופטימלי.' },
      { id: 2, pair: 'MATICUSDT', side: 'LONG', entry: '1.05', exit: '1.02', size: '500', pnl: '-15', rr: '-0.3', notes: 'MATIC לא החזיק את הפריצה. יצאתי מהר. הפסד מזערי.' },
    ],
    actualMove: "יום חזרה רך — 2 טריידים קטנים. BTC רווח קטן, MATIC הפסד קטן. סה\"כ +75$ נטו. לא מרגש אבל בהחלט OK ליום חזרה אחרי שבוע חופשה.",
    dayScore: 6,
    wins: "1. חזרתי לשוק בלי אגרסיביות — שמרתי על 0.75R כמתוכנן.\n2. MATIC cut loss מהיר — 0.3R.\n3. BTC trade היה הגיוני ומבוסס על ניתוח.",
    lessons: "1. יום חזרה חייב להיות רך — ולמדתי את זה. +75$ זה בסדר גמור.\n2. אחרי הפסקה — השוק לא בורח. אין צורך למהר.\n3. צריך עוד יום-יומיים כדי לחזור ל-rhythm המלא.",
    mistakes: "1. MATIC — נכנסתי בלי לבדוק מספיק את הוולום. הפריצה הייתה על וולום נמוך.\n2. BTC — יצאתי מוקדם מ-fear. הייתי צריך לתת לו עוד מרחב.",
    solutions: "1. ביום חזרה — רק נכסים שאני מכיר היטב (BTC, ETH). לא אלטים חדשים.\n2. קביעת TP מראש ולא לשנות בזמן אמת.",
    closing: "יום חזרה מוצלח. +75$. נטו חיובי, risk management נכון, ושום טעות גדולה. מחר מגדיל חזרה ל-1R. צעד אחר צעד.",
  },
];
