const base = {
  he: {
    title:'Orca Investment', subtitle:'מערכת מסחר מקצועית', dashboard:'לוח בקרה', journal:'יומן מסחר', calendar:'לוח שנה', analytics:'אנליטיקה', risk:'ניהול סיכונים', psychology:'פסיכולוגיה', ai:'תובנות AI', features:'מניפסט תכונות', goodMorning:'בוקר טוב, סוחר', netPnl:'רווח/הפסד נקי', profitFactor:'פקטור רווח', winRate:'אחוז הצלחה', expectancy:'תוחלת', totalTrades:'סה"כ עסקאות', bestTrade:'עסקה הטובה ביותר', worstTrade:'עסקה הגרועה ביותר', currentStreak:'רצף נוכחי', maxDrawdown:'נסיגה מקסימלית', avgWin:'ממוצע רווח', avgLoss:'ממוצע הפסד', orcaScore:'ציון Orca', edgeHealth:'בריאות יתרון', regimeFit:'התאמת משטר', equityCurve:'עקומת הון', pnlDistribution:'התפלגות רווח/הפסד', coinPerformance:'ביצועים לפי מטבע', directionAnalysis:'ניתוח כיוון', tradeNo:'#', date:'תאריך', coin:'מטבע', direction:'כיוון', entry:'כניסה', stopLoss:'סטופ לוס', exit:'יציאה', pnl:'רווח/הפסד', result:'תוצאה', riskR:'סיכון R', comments:'הערות', long:'לונג', short:'שורט', win:'רווח', loss:'הפסד', breakEven:'ברייק אוון', sun:'ראשון', mon:'שני', tue:'שלישי', wed:'רביעי', thu:'חמישי', fri:'שישי', sat:'שבת', riskMeter:'מד סיכון', dailyMaxLoss:'הפסד יומי מקסימלי', consecutiveLosses:'הפסדים רצופים', coolOff:'מצב צינון', recoveryMode:'מצב התאוששות', disciplineScore:'ציון משמעת', overtrading:'מסחר יתר', revengeTrading:'מסחר נקמה', fearGreed:'פחד/חמדנות', liveMode:'מסחר חי', reviewMode:'סקירה', researchMode:'מחקר', month:['ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'],
    // New keys
    addTrade:'הוסף עסקה', editTrade:'ערוך עסקה', deleteTrade:'מחק עסקה', deleteConfirm:'אתה בטוח?', cancel:'ביטול', save:'שמור', resetAll:'איפוס הכל', resetWarning:'פעולה זו תמחק את כל הנתונים לצמיתות. אי אפשר לבטל.', resetConfirm:'כן, מחק הכל', standardMode:'סטנדרט', alphaMode:'אלפא', theme:'נושא', midnight:'חצות', arctic:'אינדיגו ליל', ember:'אוניקס ארגמן', riskConsistency:'עקביות סיכון', riskDrift:'סחף סיכון', riskAllocation:'הקצאת סיכון', riskEvolution:'אבולוציית סיכון', generateInsights:'צור תובנות', aiSummary:'סיכום AI', monthlyEV:'תוחלת חודשית', yearlyTotal:'סה"כ שנתי', momentum:'מומנטום', noTrades:'אין עסקאות — התחל להוסיף', dollarRisk:'סיכון $', pctRisk:'סיכון %', leverage:'מינוף', positionSize:'גודל פוזיציה', orderType:'סוג פקודה', rules:'כללים', deviation:'סטייה', balance:'יתרה', weeklySummary:'סיכום שבועי', monthlyTotal:'סה"כ חודשי', streak:'רצף', heatMap:'מפת חום', settings:'הגדרות', importData:'ייבוא נתונים', exportData:'ייצוא נתונים',
  },
  en: {
    title:'Orca Investment', subtitle:'Professional Trading System', dashboard:'Dashboard', journal:'Trade Journal', calendar:'Calendar', analytics:'Analytics', risk:'Risk Management', psychology:'Psychology', ai:'AI Insights', features:'Feature Manifest', goodMorning:'Good morning, Trader', netPnl:'Net P&L', profitFactor:'Profit Factor', winRate:'Win Rate', expectancy:'Expectancy', totalTrades:'Total Trades', bestTrade:'Best Trade', worstTrade:'Worst Trade', currentStreak:'Current Streak', maxDrawdown:'Max Drawdown', avgWin:'Avg Win', avgLoss:'Avg Loss', orcaScore:'Orca Score', edgeHealth:'Edge Health', regimeFit:'Regime Fit', equityCurve:'Equity Curve', pnlDistribution:'P&L Distribution', coinPerformance:'Coin Performance', directionAnalysis:'Direction Analysis', tradeNo:'#', date:'Date', coin:'Coin', direction:'Direction', entry:'Entry', stopLoss:'Stop Loss', exit:'Exit', pnl:'P&L', result:'Result', riskR:'Risk R', comments:'Comments', long:'Long', short:'Short', win:'Win', loss:'Loss', breakEven:'Break Even', sun:'Sun', mon:'Mon', tue:'Tue', wed:'Wed', thu:'Thu', fri:'Fri', sat:'Sat', riskMeter:'Risk Meter', dailyMaxLoss:'Daily Max Loss', consecutiveLosses:'Consecutive Losses', coolOff:'Cool-Off Mode', recoveryMode:'Recovery Mode', disciplineScore:'Discipline Score', overtrading:'Overtrading', revengeTrading:'Revenge Trading', fearGreed:'Fear / Greed', liveMode:'Live Trading', reviewMode:'Review', researchMode:'Research', month:['January','February','March','April','May','June','July','August','September','October','November','December'],
    // New keys
    addTrade:'Add Trade', editTrade:'Edit Trade', deleteTrade:'Delete Trade', deleteConfirm:'Are you sure?', cancel:'Cancel', save:'Save', resetAll:'Reset All Data', resetWarning:'This will permanently delete all data. This cannot be undone.', resetConfirm:'Yes, Delete Everything', standardMode:'Standard', alphaMode:'Alpha', theme:'Theme', midnight:'Midnight', arctic:'Indigo Noir', ember:'Crimson Onyx', riskConsistency:'Risk Consistency', riskDrift:'Risk Drift', riskAllocation:'Risk Allocation', riskEvolution:'Risk Evolution', generateInsights:'Generate Insights', aiSummary:'AI Summary', monthlyEV:'Monthly EV', yearlyTotal:'Yearly Total', momentum:'Momentum', noTrades:'No trades yet — start adding', dollarRisk:'Dollar Risk', pctRisk:'% Risk', leverage:'Leverage', positionSize:'Position Size', orderType:'Order Type', rules:'Rules', deviation:'Deviation', balance:'Balance', weeklySummary:'Weekly Summary', monthlyTotal:'Monthly Total', streak:'Streak', heatMap:'Heat Map', settings:'Settings', importData:'Import Data', exportData:'Export Data',
  }
} as const;

export const i18n = base as unknown as Record<'he' | 'en', typeof base['en']>;
export type Lang = 'he' | 'en';
export type I18nStrings = typeof base['en'];

export const FEATURES = [
  { cat: 'UI/UX', n: 20, items: ['Dark premium theme with glow effects','RTL Hebrew-first layout','One-click EN/HE toggle','Responsive sidebar navigation','4 operating modes','Animated score gauges','Glass-morphism cards','Micro-interactions on hover','Multi-theme system','60fps transitions','Design tokens system','Typography hierarchy','Elevation system','Color-coded P&L','Trade detail modal','Alpha/Standard mode switching','Custom scrollbars','Toast notifications','Loading skeletons','Hard reset system'] },
  { cat: 'Analytics', n: 20, items: ['Net P&L calculation','Win rate analysis','Profit factor','Expectancy','R-multiple distribution','Equity curve','Drawdown analysis','Max drawdown tracking','Coin performance','Direction analysis','Day-of-week performance','Weekly P&L summary','Monthly EV calculation','Streak detection','Average win/loss','Best/worst trade tracking','Cumulative P&L','Drawdown depth map','Momentum indicator','Performance cards'] },
  { cat: 'Orca Scores', n: 15, items: ['Proprietary Orca Score (0-100)','Edge Health Index','Regime Fit Score','Decision quality scoring','Discipline measurement','Risk alignment tracking','Process integrity scoring','Score trend visualization','Comparative benchmarking','Score decomposition','Rolling score windows','Score alerts on decline','Historical score archive','Score vs P&L correlation','Risk Consistency Score'] },
  { cat: 'Psychology', n: 15, items: ['Discipline score tracking','Emotional state monitoring','Overtrading detection','Revenge trading alerts','Fear/Greed indicator','Confidence tracking','Pre-trade conviction score','Rule adherence monitoring','Deviation tracking','Self-sabotage detection','Behavioral pattern analysis','Decision quality vs outcome','Cool-off enforcement','Tilt detection','Conviction tracker'] },
  { cat: 'Risk Mgmt', n: 15, items: ['Dynamic risk sizing','Risk consistency scoring','Risk drift detection','Risk allocation engine','Risk evolution tracking','Daily max loss threshold','Max drawdown guardrails','Consecutive loss counter','Automatic cool-off mode','Visual risk meter','Recovery mode UI','Position size monitoring','Leverage tracking','Trade risk validation','Risk deviation warnings'] },
  { cat: 'Calendar', n: 15, items: ['Interactive calendar heatmap','Daily P&L color coding','Trade count per day','Weekly summary sidebar','Month navigation','Trade details on click','Win rate by day','P&L intensity scaling','Year selector','Monthly EV badge','Performance heat intensity','Streak highlights','Momentum indicator','Hover expansion cards','Daily slide-out summary'] },
  { cat: 'AI Engine', n: 15, items: ['Evidence-based commentary','Strength detection','Weakness identification','Risk drift monitoring','Behavioral trigger analysis','Performance shift explanation','Smart alerts','Review recommendations','Momentum shift alerts','Pattern recognition','Anomaly detection','Regime-aware insights','Generate insights on demand','Performance narrative','Executive summary'] },
  { cat: 'Data & Storage', n: 15, items: ['IndexedDB persistence','Browser restart survival','Trade add/edit/delete','Schema validation','Balance recalculation','Hard reset with confirmation','Data export (JSON)','Import trades','Multi-theme persistence','Mode persistence','Language persistence','Trade ordering','Risk validation on entry','Sound alerts','Smooth transitions'] },
];
