export const i18n = {
  he: { title:'Orca Investment', subtitle:'מערכת מסחר מקצועית', dashboard:'לוח בקרה', journal:'יומן מסחר', calendar:'לוח שנה', analytics:'אנליטיקה', risk:'ניהול סיכונים', psychology:'פסיכולוגיה', ai:'תובנות AI', features:'מניפסט תכונות', goodMorning:'בוקר טוב, סוחר', netPnl:'רווח/הפסד נקי', profitFactor:'פקטור רווח', winRate:'אחוז הצלחה', expectancy:'תוחלת', totalTrades:'סה"כ עסקאות', bestTrade:'עסקה הטובה ביותר', worstTrade:'עסקה הגרועה ביותר', currentStreak:'רצף נוכחי', maxDrawdown:'נסיגה מקסימלית', avgWin:'ממוצע רווח', avgLoss:'ממוצע הפסד', orcaScore:'ציון Orca', edgeHealth:'בריאות יתרון', regimeFit:'התאמת משטר', equityCurve:'עקומת הון', pnlDistribution:'התפלגות רווח/הפסד', coinPerformance:'ביצועים לפי מטבע', directionAnalysis:'ניתוח כיוון', tradeNo:'#', date:'תאריך', coin:'מטבע', direction:'כיוון', entry:'כניסה', stopLoss:'סטופ לוס', exit:'יציאה', pnl:'רווח/הפסד', result:'תוצאה', riskR:'סיכון R', comments:'הערות', long:'לונג', short:'שורט', win:'רווח', loss:'הפסד', breakEven:'ברייק אוון', sun:'ראשון', mon:'שני', tue:'שלישי', wed:'רביעי', thu:'חמישי', fri:'שישי', sat:'שבת', riskMeter:'מד סיכון', dailyMaxLoss:'הפסד יומי מקסימלי', consecutiveLosses:'הפסדים רצופים', coolOff:'מצב צינון', recoveryMode:'מצב התאוששות', disciplineScore:'ציון משמעת', overtrading:'מסחר יתר', revengeTrading:'מסחר נקמה', fearGreed:'פחד/חמדנות', liveMode:'מסחר חי', reviewMode:'סקירה', researchMode:'מחקר', month:['ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'] },
  en: { title:'Orca Investment', subtitle:'Professional Trading System', dashboard:'Dashboard', journal:'Trade Journal', calendar:'Calendar', analytics:'Analytics', risk:'Risk Management', psychology:'Psychology', ai:'AI Insights', features:'Feature Manifest', goodMorning:'Good morning, Trader', netPnl:'Net P&L', profitFactor:'Profit Factor', winRate:'Win Rate', expectancy:'Expectancy', totalTrades:'Total Trades', bestTrade:'Best Trade', worstTrade:'Worst Trade', currentStreak:'Current Streak', maxDrawdown:'Max Drawdown', avgWin:'Avg Win', avgLoss:'Avg Loss', orcaScore:'Orca Score', edgeHealth:'Edge Health', regimeFit:'Regime Fit', equityCurve:'Equity Curve', pnlDistribution:'P&L Distribution', coinPerformance:'Coin Performance', directionAnalysis:'Direction Analysis', tradeNo:'#', date:'Date', coin:'Coin', direction:'Direction', entry:'Entry', stopLoss:'Stop Loss', exit:'Exit', pnl:'P&L', result:'Result', riskR:'Risk R', comments:'Comments', long:'Long', short:'Short', win:'Win', loss:'Loss', breakEven:'Break Even', sun:'Sun', mon:'Mon', tue:'Tue', wed:'Wed', thu:'Thu', fri:'Fri', sat:'Sat', riskMeter:'Risk Meter', dailyMaxLoss:'Daily Max Loss', consecutiveLosses:'Consecutive Losses', coolOff:'Cool-Off Mode', recoveryMode:'Recovery Mode', disciplineScore:'Discipline Score', overtrading:'Overtrading', revengeTrading:'Revenge Trading', fearGreed:'Fear / Greed', liveMode:'Live Trading', reviewMode:'Review', researchMode:'Research', month:['January','February','March','April','May','June','July','August','September','October','November','December'] }
} as const;

export type Lang = 'he' | 'en';
export type I18nStrings = typeof i18n['en'];

export const FEATURES = [
  { cat: 'UI/UX', n: 20, items: ['Dark premium theme with glow effects','RTL Hebrew-first layout','One-click EN/HE toggle','Responsive sidebar navigation','4 operating modes','Animated score gauges','Glass-morphism cards','Micro-interactions on hover','Keyboard shortcuts','60fps transitions','Design tokens system','Typography hierarchy','Elevation system','Color-coded P&L','Trade detail modal','Drag-to-resize panels (Phase 2)','Custom scrollbars','Toast notifications (Phase 2)','Loading skeletons (Phase 2)','Onboarding tour (Phase 2)'] },
  { cat: 'Analytics', n: 20, items: ['Net P&L calculation','Win rate analysis','Profit factor','Expectancy','R-multiple distribution','Equity curve','Drawdown analysis','Max drawdown tracking','Coin performance','Direction analysis','Day-of-week performance','Weekly P&L summary','Rolling window analytics','Streak detection','Average win/loss','Best/worst trade tracking','MAE/MFE (Phase 2)','Clustering by setup (Phase 2)','Session analysis (Phase 2)','Timeframe comparison (Phase 2)'] },
  { cat: 'Orca Scores', n: 15, items: ['Proprietary Orca Score (0-100)','Edge Health Index','Regime Fit Score','Decision quality scoring','Discipline measurement','Risk alignment tracking','Process integrity scoring','Score trend visualization','Comparative benchmarking','Score decomposition','Rolling score windows','Score alerts on decline','Historical score archive','Score vs P&L correlation','Setup-specific scoring (Phase 2)'] },
  { cat: 'Psychology', n: 15, items: ['Discipline score tracking','Emotional state monitoring','Overtrading detection','Revenge trading alerts','Fear/Greed indicator','Confidence tracking','Pre-trade conviction score','Rule adherence monitoring','Deviation tracking','Self-sabotage detection','Behavioral pattern analysis','Decision quality vs outcome','Cool-off enforcement','Tilt detection','Stress indicators (Phase 2)'] },
  { cat: 'Risk Mgmt', n: 15, items: ['Daily max loss threshold','Max drawdown guardrails','Consecutive loss counter','Automatic cool-off mode','Visual risk meter','Recovery mode UI','Risk per trade tracking','Position size monitoring','Leverage tracking','Exposure calculation','Risk/reward visualization','Rule break detection','Risk governance dashboard','Cool-off timer','Progressive risk reduction (Phase 2)'] },
  { cat: 'Calendar', n: 15, items: ['Interactive calendar heatmap','Daily P&L color coding','Trade count per day','Weekly summary sidebar','Month navigation','Trade details on click','Win rate by day','P&L intensity scaling','Multi-month view (Phase 2)','Screenshot attachments (Phase 2)','Drag-drop evidence (Phase 2)','Calendar export (Phase 2)','Holiday markers (Phase 2)','Session overlays (Phase 2)','Performance comparison (Phase 2)'] },
  { cat: 'AI Insights', n: 15, items: ['Evidence-based commentary','Strength detection','Weakness identification','Risk drift monitoring','Behavioral trigger analysis','Performance shift explanation','Smart alerts','Review recommendations','What-changed analysis','Pattern recognition','Anomaly detection','Regime-aware insights','Setup optimization hints','Correlation discovery','Predictive modeling (Phase 2)'] },
  { cat: 'Data & Export', n: 15, items: ['IndexedDB persistence','Browser restart survival','Trade data import','Excel parsing','Schema validation','Duplicate detection','Google Sheets sync (Phase 2)','Two-way sync (Phase 2)','Column mapping UI (Phase 2)','Timezone settings (Phase 2)','Format validation (Phase 2)','Fee anomaly detection (Phase 2)','CSV export','JSON export','PDF reports (Phase 2)'] },
];
