/**
 * Oracle v2 — Node Catalog (42 nodes, 7 strata).
 *
 * S1 Chrono · S2 Environment · S3 Information · S4 Identity (claims) ·
 * S5 Scenario (claim-tests) · S6 Shadow · S7 Recovery.
 *
 * Source of truth for the in-memory engine and the DB seed.
 */

import type { OracleNode } from './types';

const n = (x: OracleNode): OracleNode => x;

export const ORACLE_SEED_NODES: OracleNode[] = [
  // ─── S1 CHRONO ───────────────────────────────────────────────────
  n({
    code: 'S1_SLEEP_WINDOW', stratum: 'S1', category: 'chrono', tier: 1,
    prompt_he: 'מתי באמת אתה הולך לישון בימי מסחר?',
    prompt_en: 'When do you actually fall asleep on trading days?',
    options: [
      { id: 'before_23',  label_he: 'לפני 23:00', label_en: 'Before 23:00',
        weights: { chrono_alignment: 0.9, fatigue_risk: -0.8 } },
      { id: 'p23_01',     label_he: '23:00 – 01:00', label_en: '23:00 – 01:00',
        weights: { chrono_alignment: 0.4, fatigue_risk: -0.2 } },
      { id: 'p01_03',     label_he: '01:00 – 03:00', label_en: '01:00 – 03:00',
        weights: { chrono_alignment: -0.4, fatigue_risk: 0.6 } },
      { id: 'after_03',   label_he: 'אחרי 03:00 / לא קבוע', label_en: 'After 03:00 / irregular',
        weights: { chrono_alignment: -0.9, fatigue_risk: 1.0, impulsivity: 0.3 } },
    ],
    branches: { '*': 'S1_PEAK_ENERGY' },
  }),
  n({
    code: 'S1_PEAK_ENERGY', stratum: 'S1', category: 'chrono', tier: 1,
    prompt_he: 'באיזה חלון אתה הכי חד מנטלית?',
    prompt_en: 'In which window are you most mentally sharp?',
    options: [
      { id: 'morning',  label_he: 'בוקר (06–10)', label_en: 'Morning (06–10)',
        weights: { chrono_alignment: 0.7, decision_fatigue_slope: -0.5 } },
      { id: 'midday',   label_he: 'צהריים (10–14)', label_en: 'Midday (10–14)',
        weights: { chrono_alignment: 0.5 } },
      { id: 'evening',  label_he: 'ערב (18–22)', label_en: 'Evening (18–22)',
        weights: { chrono_alignment: 0.3, fatigue_risk: 0.2 } },
      { id: 'night',    label_he: 'לילה (00–04)', label_en: 'Night (00–04)',
        weights: { chrono_alignment: -0.6, fatigue_risk: 0.8, impulsivity: 0.4 } },
    ],
    branches: { '*': 'S1_TRADE_TIME' },
  }),
  n({
    code: 'S1_TRADE_TIME', stratum: 'S1', category: 'chrono', tier: 1,
    prompt_he: 'מתי אתה בפועל מבצע את רוב הטריידים שלך?',
    prompt_en: 'When do you actually execute most of your trades?',
    options: [
      { id: 'matches_peak', label_he: 'בחלון השיא שלי', label_en: 'During my peak window',
        weights: { chrono_alignment: 1.0, rule_adherence: 0.4 } },
      { id: 'spillover',    label_he: 'גולש שעה-שעתיים מעבר', label_en: 'Spills 1–2h beyond it',
        weights: { chrono_alignment: 0.0, decision_fatigue_slope: 0.4 } },
      { id: 'late_night',   label_he: 'בעיקר אחרי 22:00', label_en: 'Mostly after 22:00',
        weights: { chrono_alignment: -0.7, fatigue_risk: 0.9, impulsivity: 0.5 } },
      { id: 'whenever',     label_he: 'מתי שהשוק "מדבר"', label_en: 'Whenever the market "talks"',
        weights: { chrono_alignment: -0.9, plan_drift: 0.8, fomo_amplitude: 0.6 } },
    ],
    branches: { '*': 'S1_PRE_OPEN_RITUAL' },
  }),
  n({
    code: 'S1_PRE_OPEN_RITUAL', stratum: 'S1', category: 'chrono', tier: 1,
    prompt_he: 'מה הדבר הראשון שאתה עושה ברגע שאתה יושב לסחור?',
    prompt_en: 'First thing you do the moment you sit down to trade?',
    options: [
      { id: 'plan',     label_he: 'כותב/מסמן תכנית יומית', label_en: 'Write / mark a daily plan',
        weights: { rule_adherence: 0.9, plan_drift: -0.8 } },
      { id: 'check_pnl',label_he: 'פותח אקסל/חשבון לראות P&L', label_en: 'Open broker to check P&L',
        weights: { loss_aversion: 0.4, rule_adherence: -0.2 } },
      { id: 'scroll',   label_he: 'גולל טוויטר/טלגרם', label_en: 'Scroll Twitter / Telegram',
        weights: { story_dependency: 0.8, narrative_susceptibility: 0.7 } },
      { id: 'jump_in',  label_he: 'מסתכל על הצ\'ארט ונכנס מיד', label_en: 'Look at chart and enter immediately',
        weights: { impulsivity: 0.9, plan_drift: 0.8, rule_adherence: -0.7 } },
    ],
    branches: { '*': 'S2_DESK_SETUP' },
  }),

  // ─── S2 ENVIRONMENT ─────────────────────────────────────────────
  n({
    code: 'S2_DESK_SETUP', stratum: 'S2', category: 'environment', tier: 1,
    prompt_he: 'איך נראה השולחן שלך בזמן מסחר?',
    prompt_en: 'What does your desk look like while trading?',
    options: [
      { id: 'clean_multi', label_he: 'נקי, מסך/ים ייעודיים, כיסא טוב', label_en: 'Clean, dedicated screen(s), good chair',
        weights: { environment_friction: -0.9, focus_capacity: 0.8 } },
      { id: 'shared',      label_he: 'שולחן משותף (משפחה/עבודה)', label_en: 'Shared desk (family / work)',
        weights: { environment_friction: 0.3, focus_capacity: -0.2 } },
      { id: 'mobile',      label_he: 'מסחר מהטלפון רוב הזמן', label_en: 'Mostly trade from phone',
        weights: { environment_friction: 0.9, focus_capacity: -0.8, impulsivity: 0.5 } },
      { id: 'bed_couch',   label_he: 'מהמיטה/ספה', label_en: 'From bed / couch',
        weights: { environment_friction: 1.0, focus_capacity: -1.0, fatigue_risk: 0.6 } },
    ],
    branches: { '*': 'S2_NOISE' },
  }),
  n({
    code: 'S2_NOISE', stratum: 'S2', category: 'environment', tier: 1,
    prompt_he: 'רעש סביבך כשאתה לוחץ "שלח"?',
    prompt_en: 'Noise around you when you hit "submit"?',
    options: [
      { id: 'silent',  label_he: 'שקט מוחלט/אוזניות', label_en: 'Silent / headphones',
        weights: { focus_capacity: 0.9, environment_friction: -0.6 } },
      { id: 'music',   label_he: 'מוזיקה רגועה ברקע', label_en: 'Calm music in background',
        weights: { focus_capacity: 0.5 } },
      { id: 'tv',      label_he: 'טלוויזיה/יוטיוב פתוחים', label_en: 'TV / YouTube on',
        weights: { focus_capacity: -0.6, narrative_susceptibility: 0.4 } },
      { id: 'chaos',   label_he: 'ילדים/בית הומה', label_en: 'Kids / busy household',
        weights: { focus_capacity: -0.9, environment_friction: 0.9, impulsivity: 0.3 } },
    ],
    branches: { '*': 'S2_ISOLATION' },
  }),
  n({
    code: 'S2_ISOLATION', stratum: 'S2', category: 'environment', tier: 1,
    prompt_he: 'אתה מדבר עם מישהו על טריידים בזמן אמת?',
    prompt_en: 'Do you talk to someone about live trades in real time?',
    options: [
      { id: 'none',     label_he: 'אף אחד — שקט תפעולי', label_en: 'No one — operational silence',
        weights: { social_pressure: -0.8, story_dependency: -0.3 } },
      { id: 'mentor',   label_he: 'מנטור/חבר עם ניסיון', label_en: 'Mentor / experienced peer',
        weights: { social_pressure: -0.3, rule_adherence: 0.4 } },
      { id: 'group',    label_he: 'קבוצת טלגרם/דיסקורד', label_en: 'Telegram / Discord group',
        weights: { social_pressure: 0.7, story_dependency: 0.6, fomo_amplitude: 0.5 } },
      { id: 'public',   label_he: 'מצייץ/מפרסם את הפוזיציות', label_en: 'Post / tweet my positions',
        weights: { social_pressure: 1.0, ego_attribution: 0.9, win_attribution_self: 0.7 } },
    ],
    branches: { '*': 'S2_INTERRUPTIONS' },
  }),

  // ─── S3 INFORMATION ─────────────────────────────────────────────
  n({
    code: 'S2_INTERRUPTIONS', stratum: 'S2', category: 'environment', tier: 1,
    prompt_he: 'בממוצע, כמה הפרעות (טלפון, הודעה, אדם) אתה חווה בשעת מסחר?',
    prompt_en: 'On average, how many interruptions per trading hour?',
    options: [
      { id: 'zero', label_he: '0 — מוגן לחלוטין',  label_en: '0 — fully protected',
        weights: { focus_capacity: 1.0, environment_friction: -0.9 } },
      { id: 'few',  label_he: '1–3',  label_en: '1–3', weights: { focus_capacity: 0.2 } },
      { id: 'many', label_he: '4–8',  label_en: '4–8',
        weights: { focus_capacity: -0.6, environment_friction: 0.7 } },
      { id: 'flood',label_he: '8+ — בלתי נשלט', label_en: '8+ — uncontrolled',
        weights: { focus_capacity: -1.0, environment_friction: 1.0, decision_fatigue_slope: 0.6 } },
    ],
    branches: { '*': 'S3_FEEDS' },
  }),
  n({
    code: 'S3_FEEDS', stratum: 'S3', category: 'information', tier: 1,
    prompt_he: 'מאיפה אתה צורך את רוב המידע על השוק?',
    prompt_en: 'Where do you consume most of your market information?',
    options: [
      { id: 'data',    label_he: 'דאטה ראשונית (בורסה, on-chain, מאקרו)', label_en: 'Primary data (exchange, on-chain, macro)',
        weights: { info_diet_quality: 1.0, narrative_susceptibility: -0.8 } },
      { id: 'longform',label_he: 'בלוגים/ניוזלטרים מעמיקים', label_en: 'In-depth blogs / newsletters',
        weights: { info_diet_quality: 0.6, narrative_susceptibility: -0.2 } },
      { id: 'twitter', label_he: 'טוויטר/CT (Crypto Twitter)', label_en: 'Twitter / Crypto-Twitter',
        weights: { info_diet_quality: -0.4, narrative_susceptibility: 0.7, story_dependency: 0.6 } },
      { id: 'tiktok',  label_he: 'יוטיוב שורטס / TikTok / Reels', label_en: 'YouTube Shorts / TikTok / Reels',
        weights: { info_diet_quality: -1.0, narrative_susceptibility: 1.0, fomo_amplitude: 0.8 } },
    ],
    branches: { '*': 'S3_INFLUENCERS' },
  }),
  n({
    code: 'S3_INFLUENCERS', stratum: 'S3', category: 'information', tier: 1,
    prompt_he: 'יש לך 1–3 "קולות" שאתה בודק לפני החלטת מסחר?',
    prompt_en: 'Do you have 1–3 "voices" you check before a trading decision?',
    options: [
      { id: 'none',    label_he: 'לא — רק המערכת שלי', label_en: 'No — only my own system',
        weights: { narrative_susceptibility: -0.9, rule_adherence: 0.7 } },
      { id: 'one_two', label_he: '1–2, ולדעתי הם אובייקטיביים', label_en: '1–2, and I find them objective',
        weights: { narrative_susceptibility: 0.2 } },
      { id: 'many',    label_he: '3+ אנליסטים שאני עוקב אחריהם', label_en: '3+ analysts I follow',
        weights: { narrative_susceptibility: 0.7, story_dependency: 0.6 } },
      { id: 'live_chat', label_he: 'יש לי "צ\'אט חי" עם גורו', label_en: 'I have a live chat with a guru',
        weights: { narrative_susceptibility: 1.0, story_dependency: 1.0, ego_attribution: 0.4 } },
    ],
    branches: { '*': 'S3_NEWS_CADENCE' },
  }),
  n({
    code: 'S3_NEWS_CADENCE', stratum: 'S3', category: 'information', tier: 1,
    prompt_he: 'באמצע פוזיציה — כמה פעמים בשעה אתה רץ לבדוק חדשות?',
    prompt_en: 'Mid-position — how often per hour do you refresh news?',
    options: [
      { id: 'never',   label_he: 'אפס — סומך על התכנית', label_en: 'Zero — trust the plan',
        weights: { plan_drift: -0.9, info_diet_quality: 0.6 } },
      { id: 'planned', label_he: 'בנקודות מתוכננות בלבד', label_en: 'Only at planned checkpoints',
        weights: { plan_drift: -0.4, rule_adherence: 0.6 } },
      { id: 'often',   label_he: 'כל 10–15 דקות', label_en: 'Every 10–15 minutes',
        weights: { plan_drift: 0.6, narrative_susceptibility: 0.5 } },
      { id: 'constant',label_he: 'באופן רציף — לא יכול להפסיק', label_en: 'Constantly — can\'t stop',
        weights: { plan_drift: 1.0, narrative_susceptibility: 0.9, fomo_amplitude: 0.7 } },
    ],
    branches: { '*': 'S3_SOCIAL_PROOF' },
  }),
  n({
    code: 'S3_SOCIAL_PROOF', stratum: 'S3', category: 'information', tier: 1,
    prompt_he: 'ראית סטאפ שמתאים לך — אבל אף אחד בקבוצות לא מדבר עליו. מה הסיכוי שתיכנס?',
    prompt_en: 'You see a setup that fits you — but no one in your groups is talking about it. Likelihood you enter?',
    options: [
      { id: 'high',  label_he: 'גבוה — הסיגנל שלי = הסיגנל שלי', label_en: 'High — my signal is my signal',
        weights: { narrative_susceptibility: -0.9, rule_adherence: 0.8 } },
      { id: 'mid',   label_he: 'בינוני — אבדוק שוב את התזה', label_en: 'Medium — I re-check the thesis',
        weights: { narrative_susceptibility: 0.0 } },
      { id: 'low',   label_he: 'נמוך — חוסר אישור מטריד', label_en: 'Low — lack of confirmation bothers me',
        weights: { narrative_susceptibility: 0.7, social_pressure: 0.6 } },
      { id: 'zero',  label_he: 'אפס — אם אף אחד לא רואה, אני טועה', label_en: 'Zero — if no one sees it, I\'m wrong',
        weights: { narrative_susceptibility: 1.0, social_pressure: 1.0, rule_adherence: -0.6 } },
    ],
    branches: { '*': 'S4_CLAIM_PATIENT' },
  }),

  // ─── S4 IDENTITY (claim layer — each emits a claim_token) ───────
  n({
    code: 'S4_CLAIM_PATIENT', stratum: 'S4', category: 'identity', tier: 2,
    claim_token: 'claim:patient',
    prompt_he: 'איך תתאר את עצמך כסוחר?',
    prompt_en: 'How would you describe yourself as a trader?',
    options: [
      { id: 'patient',     label_he: 'סבלני — מחכה לסטאפ',         label_en: 'Patient — wait for setups',
        weights: { self_narrative_gap: 0.2, rule_adherence: 0.5 } },
      { id: 'opportunist', label_he: 'הזדמנותי — מנצל תזוזה',       label_en: 'Opportunistic — capture moves',
        weights: { impulsivity: 0.3 } },
      { id: 'reactive',    label_he: 'תגובתי — מגיב לשוק',          label_en: 'Reactive — respond to market',
        weights: { impulsivity: 0.6 } },
      { id: 'compulsive',  label_he: 'יודע שאני נכנס יותר מדי',     label_en: 'I know I overtrade',
        weights: { impulsivity: 0.9, self_narrative_gap: -0.5 } },
    ],
    branches: { '*': 'S5_BREAKOUT_TEST' },
  }),
  n({
    code: 'S4_CLAIM_DISCIPLINED', stratum: 'S4', category: 'identity', tier: 2,
    claim_token: 'claim:disciplined',
    prompt_he: 'באיזו תדירות אתה עוקב אחרי המערכת שלך 100%?',
    prompt_en: 'How often do you follow your system 100%?',
    options: [
      { id: 'always',  label_he: 'תמיד', label_en: 'Always',
        weights: { rule_adherence: 0.5, self_narrative_gap: 0.4 } },
      { id: 'mostly',  label_he: 'ברוב המקרים', label_en: 'Most of the time', weights: { rule_adherence: 0.2 } },
      { id: 'half',    label_he: 'בערך חצי', label_en: 'About half',  weights: { rule_adherence: -0.3, plan_drift: 0.4 } },
      { id: 'rarely',  label_he: 'נדיר — אני מאלתר', label_en: 'Rarely — I improvise', weights: { rule_adherence: -0.9, plan_drift: 0.9 } },
    ],
    branches: { '*': 'S5_GAP_TEST' },
  }),
  n({
    code: 'S4_CLAIM_CONTRARIAN', stratum: 'S4', category: 'identity', tier: 2,
    claim_token: 'claim:contrarian',
    prompt_he: 'איך אתה מגיב לקונצנזוס בשוק?',
    prompt_en: 'How do you respond to market consensus?',
    options: [
      { id: 'fade_it',  label_he: 'אני מנגד — סוחר נגד הזרם',  label_en: 'I fade it — trade against the crowd',
        weights: { story_dependency: -0.6 } },
      { id: 'with_it',  label_he: 'הולך איתו — טרנד הוא טרנד', label_en: 'I go with it — trend is trend',
        weights: { story_dependency: 0.3, narrative_susceptibility: 0.3 } },
      { id: 'depends',  label_he: 'תלוי בסטאפ',                 label_en: 'Depends on the setup', weights: { rule_adherence: 0.4 } },
      { id: 'follow_kol', label_he: 'הולך אחרי אנליסט מועדף',   label_en: 'I follow my favorite analyst',
        weights: { story_dependency: 1.0, narrative_susceptibility: 1.0 } },
    ],
    branches: { '*': 'S5_GURU_TEST' },
  }),
  n({
    code: 'S4_CLAIM_RISK_AWARE', stratum: 'S4', category: 'identity', tier: 2,
    claim_token: 'claim:risk_aware',
    prompt_he: 'מהו עיקרון הסיכון העליון שלך?',
    prompt_en: 'What is your top risk principle?',
    options: [
      { id: 'fixed_r',  label_he: 'R קבוע לכל טרייד, ללא יוצא מן הכלל', label_en: 'Fixed R per trade, no exceptions',
        weights: { rule_adherence: 0.8, leverage_hubris: -0.7 } },
      { id: 'conviction',label_he: 'יותר R לסטאפ עם הכרה גבוהה',         label_en: 'More R on high-conviction setups',
        weights: { leverage_hubris: 0.4 } },
      { id: 'gut',       label_he: 'תחושה — לפי "איך אני מרגיש"',         label_en: 'Gut — based on "how I feel"',
        weights: { rule_adherence: -0.7, impulsivity: 0.6 } },
      { id: 'all_in',    label_he: 'הולך גדול כשאני בטוח',                 label_en: 'Go big when I\'m sure',
        weights: { leverage_hubris: 1.0, ego_attribution: 0.8 } },
    ],
    branches: { '*': 'S5_CONVICTION_TEST' },
  }),
  n({
    code: 'S4_CLAIM_OBJECTIVE', stratum: 'S4', category: 'identity', tier: 2,
    claim_token: 'claim:objective',
    prompt_he: 'כשאתה מפסיד טרייד — מה הסיבה הראשונה שעולה לך?',
    prompt_en: 'When you lose a trade — first reason that comes to mind?',
    options: [
      { id: 'me',     label_he: 'אני — סטיתי או טעיתי',          label_en: 'Me — I drifted or erred',
        weights: { loss_attribution_external: -0.8 } },
      { id: 'system', label_he: 'המערכת — צריכה כיול',            label_en: 'The system — needs calibration',
        weights: { loss_attribution_external: 0.2 } },
      { id: 'market', label_he: 'השוק — לא הגיוני',                label_en: 'The market — irrational',
        weights: { loss_attribution_external: 0.8 } },
      { id: 'others', label_he: 'מאנפלטורים/ווייל סטריט',          label_en: 'Manipulators / Wall Street',
        weights: { loss_attribution_external: 1.0, ego_attribution: 0.6 } },
    ],
    branches: { '*': 'S6_BLAME_PROBE' },
  }),

  // ─── S5 SCENARIO (claim-tests) ──────────────────────────────────
  n({
    code: 'S5_BREAKOUT_TEST', stratum: 'S5', category: 'scenario', tier: 2,
    counter_for: 'claim:patient',
    prompt_he: 'BTC פורץ התנגדות מרכזית בנפח עולה. אין לך תכנית מוקדמת לרמה הזו. 3 שניות — מה אתה עושה?',
    prompt_en: 'BTC breaks a key resistance on rising volume. You had no plan for this level. 3 seconds — what do you do?',
    options: [
      { id: 'enter_market', label_he: 'נכנס מיד ב-Market', label_en: 'Enter immediately at market',
        weights: { impulsivity: 0.9, plan_drift: 0.7, fomo_amplitude: 0.8 } },
      { id: 'small_probe',  label_he: 'נכנס בפוזיציה קטנה לבדיקה', label_en: 'Enter a small probe position',
        weights: { impulsivity: 0.4, rule_adherence: 0.2 } },
      { id: 'wait_retest',  label_he: 'מחכה לרי-טסט', label_en: 'Wait for a retest',
        weights: { impulsivity: -0.6, rule_adherence: 0.7 } },
      { id: 'skip_setup',   label_he: 'לא נכנס — אין תכנית', label_en: 'Skip — no plan',
        weights: { impulsivity: -0.9, rule_adherence: 0.9, plan_drift: -0.8 } },
    ],
    branches: {
      enter_market: 'S5_IMMEDIATE_RED',
      small_probe:  'S5_IMMEDIATE_RED',
      '*':          'S5_GAP_TEST',
    },
  }),
  n({
    code: 'S5_GAP_TEST', stratum: 'S5', category: 'scenario', tier: 2,
    counter_for: 'claim:disciplined',
    prompt_he: 'זיהית סטאפ מושלם לפי המערכת שלך, אבל הוא קפץ 1.2% לפני שלחצת "שלח". מה תעשה?',
    prompt_en: 'You spotted a perfect setup, but it gapped 1.2% before you hit "submit." What now?',
    options: [
      { id: 'chase',  label_he: 'רודף — לא רוצה לפספס',  label_en: 'Chase — don\'t want to miss',
        weights: { impulsivity: 0.9, fomo_amplitude: 1.0, rule_adherence: -0.7 } },
      { id: 'reduce', label_he: 'נכנס בגודל קטן יותר',     label_en: 'Enter with reduced size',
        weights: { impulsivity: 0.2, rule_adherence: 0.4 } },
      { id: 'pass',   label_he: 'מוותר — הסטאפ נפגע',     label_en: 'Pass — setup invalidated',
        weights: { impulsivity: -0.9, rule_adherence: 1.0, plan_drift: -0.9 } },
      { id: 'force',  label_he: 'משנה את היעדים שיתאימו',  label_en: 'Adjust targets to make it fit',
        weights: { plan_drift: 1.0, rule_adherence: -1.0, narrative_susceptibility: 0.5 } },
    ],
    branches: { '*': 'S5_IMMEDIATE_RED' },
  }),
  n({
    code: 'S5_IMMEDIATE_RED', stratum: 'S5', category: 'scenario', tier: 2,
    prompt_he: 'דקה אחרי הכניסה אתה ב-0.7R הפסד. הסטופ עוד לא נגוע. גופך מגיב לפני הראש. הצעד?',
    prompt_en: 'A minute after entry: -0.7R. Stop not touched. Body reacts before mind. Move?',
    options: [
      { id: 'tighten_stop', label_he: 'מקרב סטופ כדי "להגן"', label_en: 'Tighten stop to "protect"',
        weights: { loss_aversion: 0.9, stop_moving_tendency: 1.0 } },
      { id: 'add_average',  label_he: 'מוסיף — אני "צודק"', label_en: 'Add — I\'m "right"',
        weights: { loss_aversion: 0.4, impulsivity: 0.7, ego_attribution: 0.7 } },
      { id: 'hold_plan',    label_he: 'נשאר עם התכנית', label_en: 'Stick to plan',
        weights: { loss_aversion: -0.7, rule_adherence: 1.0 } },
      { id: 'exit_early',   label_he: 'יוצא עכשיו — להפסיק את הכאב', label_en: 'Exit now — stop the pain',
        weights: { loss_aversion: 1.0, freeze_at_red: 0.8, rule_adherence: -0.7 } },
    ],
    branches: { '*': 'S5_GURU_TEST' },
  }),
  n({
    code: 'S5_GURU_TEST', stratum: 'S5', category: 'scenario', tier: 2,
    counter_for: 'claim:contrarian',
    prompt_he: 'חבר שולח טוויט של אנליסט: "BTC ל-200K עד סוף הרבעון". תגובתך?',
    prompt_en: 'A friend forwards an analyst tweet: "BTC to 200K by Q-end." Your response?',
    options: [
      { id: 'believe_act', label_he: 'מגדיל אקספוז\'ר על בסיס זה', label_en: 'Increase exposure based on this',
        weights: { story_dependency: 1.0, narrative_susceptibility: 0.9, leverage_hubris: 0.6 } },
      { id: 'verify_data', label_he: 'בודק את הדאטה לבד',           label_en: 'Verify the data myself',
        weights: { story_dependency: -0.8, rule_adherence: 0.5 } },
      { id: 'ignore',      label_he: 'מתעלם — לא רלוונטי לתכנית',   label_en: 'Ignore — irrelevant',
        weights: { story_dependency: -1.0, plan_drift: -0.7 } },
      { id: 'fade',        label_he: 'מנגד — אם ויראלי, תומחר',     label_en: 'Fade — if viral, priced in',
        weights: { story_dependency: -0.4, narrative_susceptibility: -0.6 } },
    ],
    branches: { '*': 'S5_CONVICTION_TEST' },
  }),
  n({
    code: 'S5_CONVICTION_TEST', stratum: 'S5', category: 'scenario', tier: 2,
    counter_for: 'claim:risk_aware',
    prompt_he: 'אמרת שאתה סוחר ב-1% סיכון. הסטאפ הבא הוא "A+". כמה אתה באמת מסכן?',
    prompt_en: 'You said you risk 1% per trade. The next setup is "A+." How much do you actually risk?',
    options: [
      { id: 'one',      label_he: 'בדיוק 1%', label_en: 'Exactly 1%',
        weights: { rule_adherence: 1.0, leverage_hubris: -0.7 } },
      { id: 'one_five', label_he: '1.5% — סטאפ חזק', label_en: '1.5% — stronger setup',
        weights: { rule_adherence: -0.4, leverage_hubris: 0.4 } },
      { id: 'two_plus', label_he: '2–3% — "אני בטוח"', label_en: '2–3% — "I\'m sure"',
        weights: { rule_adherence: -0.9, leverage_hubris: 1.0, ego_attribution: 0.6 } },
      { id: 'half',     label_he: 'פחות — אני מפחד', label_en: 'Less — I\'m scared',
        weights: { loss_aversion: 0.7, freeze_at_red: 0.5 } },
    ],
    branches: { '*': 'S5_LATE_NIGHT_BRIDGE' },
  }),
  n({
    code: 'S5_LATE_NIGHT_BRIDGE', stratum: 'S5', category: 'scenario', tier: 3,
    prompt_he: '02:14 בלילה. סקרולת CT 40 דקות. רואים סטאפ "מטורף". התכנית שלך לא רואה אותו. הצעד?',
    prompt_en: '02:14 at night. Scrolled CT for 40 minutes. You see a "crazy" setup. Your plan doesn\'t see it. Move?',
    options: [
      { id: 'enter',  label_he: 'נכנס — מתי עוד תזדמן כזו?', label_en: 'Enter — when else does one come?',
        weights: { fatigue_risk: 0.8, impulsivity: 1.0, fomo_amplitude: 1.0, plan_drift: 0.9 } },
      { id: 'note',   label_he: 'מתעד ובודק מחר בבוקר',     label_en: 'Note it, check tomorrow morning',
        weights: { rule_adherence: 0.9, fatigue_risk: -0.4 } },
      { id: 'close_app', label_he: 'סוגר את האפליקציה',     label_en: 'Close the app',
        weights: { rule_adherence: 1.0, fatigue_risk: -0.7, impulsivity: -0.9 } },
      { id: 'small',  label_he: 'נכנס קטן "לצחוק"',          label_en: 'Enter small "for fun"',
        weights: { impulsivity: 0.8, plan_drift: 0.7, fatigue_risk: 0.5 } },
    ],
    branches: { '*': 'S6_REVENGE_PROBE' },
  }),

  // ─── S6 SHADOW ──────────────────────────────────────────────────
  n({
    code: 'S6_BLAME_PROBE', stratum: 'S6', category: 'shadow', tier: 2,
    prompt_he: 'הפסדת 3 ברצף. השבוע נסגר ב-4R-. מה הכי קרוב לאמת הפנימית שלך?',
    prompt_en: 'Lost 3 in a row. Week closed -4R. Closest to your inner truth?',
    options: [
      { id: 'market_fault', label_he: 'השוק לא הגיוני השבוע', label_en: 'The market made no sense',
        weights: { loss_attribution_external: 0.9, ego_attribution: 0.6 } },
      { id: 'me_fault',     label_he: 'אני סטיתי מהמערכת',    label_en: 'I drifted from my system',
        weights: { loss_attribution_external: -0.9, rule_adherence: 0.6 } },
      { id: 'mixed',        label_he: 'גם וגם — וזה בסדר',    label_en: 'Both — and that\'s ok',
        weights: { loss_attribution_external: -0.2 } },
      { id: 'no_loss',      label_he: 'לא הפסדתי באמת — אחזיר',label_en: 'Haven\'t really lost — I\'ll get it back',
        weights: { loss_attribution_external: 1.0, ego_attribution: 1.0, revenge_trade_propensity: 1.0 } },
    ],
    branches: { '*': 'S6_FOMO_PROBE' },
  }),
  n({
    code: 'S6_REVENGE_PROBE', stratum: 'S6', category: 'shadow', tier: 2,
    prompt_he: 'יצאת מסטופ. ראית את המחיר חוזר בכיוון שלך 30 שניות אחר כך. הרגש הראשון?',
    prompt_en: 'You got stopped. 30 seconds later price reverses your way. First feeling?',
    options: [
      { id: 'rage',   label_he: 'זעם — "השוק רודף אותי"', label_en: 'Rage — "the market is hunting me"',
        weights: { revenge_trade_propensity: 1.0, loss_attribution_external: 0.9 } },
      { id: 'reenter',label_he: 'דחף לחזור מיד פנימה',     label_en: 'Urge to re-enter immediately',
        weights: { revenge_trade_propensity: 0.9, impulsivity: 0.8 } },
      { id: 'observe',label_he: 'תיעוד — "מעניין, למד"',   label_en: 'Notation — "interesting, learn"',
        weights: { revenge_trade_propensity: -0.9, rule_adherence: 0.7 } },
      { id: 'walk',   label_he: 'קם מהשולחן ל-15 דקות',     label_en: 'Walk away from desk for 15 min',
        weights: { revenge_trade_propensity: -1.0, recovery_health: 0.8 } },
    ],
    branches: { '*': 'S6_FOMO_PROBE' },
  }),
  n({
    code: 'S6_FOMO_PROBE', stratum: 'S6', category: 'shadow', tier: 2,
    prompt_he: 'מטבע שלא עוקב אחריו עושה +20% תוך 4 שעות. הראשונה ש"קופצת"?',
    prompt_en: 'A coin you don\'t follow does +20% in 4 hours. First thing that "pops"?',
    options: [
      { id: 'missed',  label_he: '"איך פספסתי את זה"', label_en: '"How did I miss this"',
        weights: { fomo_amplitude: 1.0, ego_attribution: 0.4 } },
      { id: 'chase',   label_he: 'בודק אם עוד אפשר להיכנס', label_en: 'Check if I can still enter',
        weights: { fomo_amplitude: 0.9, impulsivity: 0.7 } },
      { id: 'curious', label_he: 'מסקרן, אבל לא רלוונטי לי', label_en: 'Curious, but irrelevant to me',
        weights: { fomo_amplitude: -0.4, rule_adherence: 0.5 } },
      { id: 'nothing', label_he: 'שום דבר — לא בתחום שלי', label_en: 'Nothing — not in my scope',
        weights: { fomo_amplitude: -1.0, rule_adherence: 0.9 } },
    ],
    branches: { '*': 'S6_EGO_PROBE' },
  }),
  n({
    code: 'S6_EGO_PROBE', stratum: 'S6', category: 'shadow', tier: 2,
    prompt_he: 'טרייד מנצח של +5R. למי אתה מספר תוך 24 שעות?',
    prompt_en: 'A +5R winner. Who do you tell within 24 hours?',
    options: [
      { id: 'no_one',  label_he: 'אף אחד — תיעוד פרטי בלבד', label_en: 'No one — private log only',
        weights: { ego_attribution: -0.9, win_attribution_self: -0.3 } },
      { id: 'mentor',  label_he: 'מנטור/שותף שיחה', label_en: 'Mentor / accountability partner',
        weights: { ego_attribution: -0.3, social_pressure: 0.2 } },
      { id: 'group',   label_he: 'קבוצה סגורה — תרבות הוקרה', label_en: 'Private group — culture of recognition',
        weights: { ego_attribution: 0.5, social_pressure: 0.5 } },
      { id: 'public',  label_he: 'מצייץ סקרין של ה-P&L', label_en: 'Tweet a P&L screenshot',
        weights: { ego_attribution: 1.0, win_attribution_self: 1.0, social_pressure: 0.9 } },
    ],
    branches: { '*': 'S6_DENIAL_PROBE' },
  }),
  n({
    code: 'S6_DENIAL_PROBE', stratum: 'S6', category: 'shadow', tier: 2,
    prompt_he: 'אתה ב-1.5R מתחת לסטופ המקורי שלך. הוא כבר לא קיים בפועל. למה?',
    prompt_en: 'You\'re 1.5R below your original stop. The stop no longer effectively exists. Why?',
    options: [
      { id: 'never_happens', label_he: 'זה לא קורה לי',         label_en: 'This doesn\'t happen to me',
        weights: { self_narrative_gap: 1.0, loss_attribution_external: 0.8 } },
      { id: 'gave_chance',   label_he: 'נתתי לטרייד "עוד צ\'אנס"',label_en: 'Gave the trade "another chance"',
        weights: { stop_moving_tendency: 1.0, plan_drift: 0.8 } },
      { id: 'froze',         label_he: 'קפאתי — לא יכולתי ללחוץ',label_en: 'I froze — couldn\'t click',
        weights: { freeze_at_red: 1.0, loss_aversion: 0.8 } },
      { id: 'rare',          label_he: 'נדיר, אבל קורה',          label_en: 'Rare, but happens',
        weights: { stop_moving_tendency: 0.3 } },
    ],
    branches: { '*': 'S7_POST_LOSS_RITUAL' },
  }),
  n({
    code: 'S6_SECRECY_PROBE', stratum: 'S6', category: 'shadow', tier: 3,
    prompt_he: 'יש לך טרייד שלא תיעדת ב-30 הימים האחרונים?',
    prompt_en: 'Is there a trade you did NOT log in the last 30 days?',
    options: [
      { id: 'never',  label_he: 'אף פעם — הכל נכנס לג\'ורנל', label_en: 'Never — everything goes in the journal',
        weights: { rule_adherence: 1.0, self_narrative_gap: -0.6 } },
      { id: 'one',    label_he: '1–2 קטנים',                  label_en: '1–2 small ones',
        weights: { self_narrative_gap: 0.3 } },
      { id: 'few',    label_he: 'כמה — בעיקר מפסידים',        label_en: 'A few — mostly losers',
        weights: { self_narrative_gap: 0.9, loss_attribution_external: 0.6 } },
      { id: 'many',   label_he: 'הרבה — לא רוצה לראות',        label_en: 'Many — I don\'t want to see',
        weights: { self_narrative_gap: 1.0, freeze_at_red: 0.7, rule_adherence: -0.9 } },
    ],
    branches: { '*': 'S7_POST_LOSS_RITUAL' },
  }),

  // ─── S7 RECOVERY ────────────────────────────────────────────────
  n({
    code: 'S7_POST_LOSS_RITUAL', stratum: 'S7', category: 'recovery', tier: 2,
    prompt_he: 'יום של -3R. הריטואל שלך אחרי סגירת המסכים?',
    prompt_en: 'A -3R day. Your ritual after closing screens?',
    options: [
      { id: 'review',  label_he: 'תיעוד וניתוח של כל טרייד',  label_en: 'Log + analyse each trade',
        weights: { recovery_health: 1.0, rule_adherence: 0.7 } },
      { id: 'sport',   label_he: 'ספורט / הליכה / מקלחת',     label_en: 'Sport / walk / shower',
        weights: { recovery_health: 0.8 } },
      { id: 'scroll',  label_he: 'גולל ברשתות עד שאני נרגע',  label_en: 'Scroll socials until I calm',
        weights: { recovery_health: -0.5, narrative_susceptibility: 0.5 } },
      { id: 'drink',   label_he: 'אלכוהול/משחק/בינג\' לשכוח',  label_en: 'Alcohol / gaming / binge to forget',
        weights: { recovery_health: -1.0, freeze_at_red: 0.6 } },
    ],
    branches: { '*': 'S7_JOURNAL_HABIT' },
  }),
  n({
    code: 'S7_JOURNAL_HABIT', stratum: 'S7', category: 'recovery', tier: 2,
    prompt_he: 'באיזו תדירות אתה כותב סיכום שבועי בכתב?',
    prompt_en: 'How often do you write a weekly review in your own words?',
    options: [
      { id: 'every',   label_he: 'כל שבוע — בלי דילוגים',  label_en: 'Every week — no skips',
        weights: { recovery_health: 1.0, rule_adherence: 0.8 } },
      { id: 'most',    label_he: 'רוב השבועות',             label_en: 'Most weeks',
        weights: { recovery_health: 0.5 } },
      { id: 'rare',    label_he: 'נדיר — רק אחרי שבועות גרועים', label_en: 'Rare — only after bad weeks',
        weights: { recovery_health: -0.4, self_narrative_gap: 0.4 } },
      { id: 'never',   label_he: 'אף פעם',                  label_en: 'Never',
        weights: { recovery_health: -1.0, self_narrative_gap: 0.8 } },
    ],
    branches: { '*': 'S7_WITHDRAWAL' },
  }),
  n({
    code: 'S7_WITHDRAWAL', stratum: 'S7', category: 'recovery', tier: 2,
    prompt_he: 'אחרי הפסד גדול, מה קורה לחיי החברה שלך?',
    prompt_en: 'After a big loss, what happens to your social life?',
    options: [
      { id: 'normal',     label_he: 'הכל כרגיל',           label_en: 'Everything as usual',
        weights: { recovery_health: 0.9 } },
      { id: 'short',      label_he: 'שעות-יום של ריחוק',    label_en: 'Hours-day of distance',
        weights: { recovery_health: 0.2 } },
      { id: 'days',       label_he: 'ימים של הסתגרות',       label_en: 'Days of withdrawal',
        weights: { recovery_health: -0.7, self_narrative_gap: 0.6 } },
      { id: 'weeks',      label_he: 'שבועות — מסתיר את ה-P&L',label_en: 'Weeks — I hide the P&L',
        weights: { recovery_health: -1.0, self_narrative_gap: 1.0, ego_attribution: 0.6 } },
    ],
    branches: { '*': 'S7_RETURN_TRIGGER' },
  }),
  n({
    code: 'S7_RETURN_TRIGGER', stratum: 'S7', category: 'recovery', tier: 2,
    prompt_he: 'מה מחזיר אותך לסחור אחרי הפסקה כפויה?',
    prompt_en: 'What brings you back to trading after a forced break?',
    options: [
      { id: 'plan',    label_he: 'תכנית חדשה כתובה',     label_en: 'A new written plan',
        weights: { recovery_health: 1.0, rule_adherence: 1.0 } },
      { id: 'urge',    label_he: 'דחף — "מספיק"',          label_en: 'Urge — "enough"',
        weights: { recovery_health: -0.3, impulsivity: 0.7 } },
      { id: 'fomo',    label_he: 'ראיתי תזוזה שלא יכולתי לפספס', label_en: 'A move I couldn\'t miss',
        weights: { recovery_health: -0.8, fomo_amplitude: 1.0, revenge_trade_propensity: 0.5 } },
      { id: 'money',   label_he: 'חייב להחזיר את ההפסד',   label_en: 'Need to recover the loss',
        weights: { recovery_health: -1.0, revenge_trade_propensity: 1.0, loss_aversion: 0.8 } },
    ],
    branches: { '*': 'PROBE_IMPULSIVITY_QUANT' },
  }),

  // ─── DEPTH PROBES ───────────────────────────────────────────────
  n({
    code: 'PROBE_IMPULSIVITY_QUANT', stratum: 'S5', category: 'depth_probe', tier: 3,
    prompt_he: 'באיזה אחוז מהטריידים שלך ב-30 הימים האחרונים נכנסת בלי תכנית כתובה מראש?',
    prompt_en: 'In what % of your trades over the last 30 days did you enter without a written plan?',
    options: [
      { id: 'lt10',  label_he: '<10%',  label_en: '<10%',  weights: { impulsivity: -0.8, rule_adherence: 0.7 } },
      { id: 'p10_30',label_he: '10–30%',label_en: '10–30%',weights: { impulsivity: 0.3, rule_adherence: 0.1 } },
      { id: 'p30_60',label_he: '30–60%',label_en: '30–60%',weights: { impulsivity: 0.7, plan_drift: 0.6 } },
      { id: 'gt60',  label_he: '>60%',  label_en: '>60%',  weights: { impulsivity: 1.0, plan_drift: 0.9, rule_adherence: -0.9 } },
    ],
    branches: {},
  }),
  n({
    code: 'PROBE_LOSS_AVERSION_QUANT', stratum: 'S5', category: 'depth_probe', tier: 3,
    prompt_he: 'מתוך 100 הטריידים האחרונים, באיזה אחוז הזזת את הסטופ אחורה?',
    prompt_en: 'Of your last 100 trades, in what % did you move your stop further away?',
    options: [
      { id: 'never', label_he: '0%',    label_en: '0%',    weights: { stop_moving_tendency: -1.0, rule_adherence: 0.9 } },
      { id: 'few',   label_he: '<10%',  label_en: '<10%',  weights: { stop_moving_tendency: 0.2 } },
      { id: 'some',  label_he: '10–30%',label_en: '10–30%',weights: { stop_moving_tendency: 0.7, loss_aversion: 0.6 } },
      { id: 'often', label_he: '>30%',  label_en: '>30%',  weights: { stop_moving_tendency: 1.0, loss_aversion: 0.9, rule_adherence: -0.8 } },
    ],
    branches: {},
  }),
  n({
    code: 'PROBE_STORY_QUANT', stratum: 'S5', category: 'depth_probe', tier: 3,
    prompt_he: 'באיזה אחוז מהטריידים שלך הופעלת בהשפעה ישירה של פוסט/וידאו של מישהו אחר?',
    prompt_en: 'In what % of your trades were you directly influenced by someone else\'s post/video?',
    options: [
      { id: 'never', label_he: '0%',   label_en: '0%',    weights: { story_dependency: -1.0, narrative_susceptibility: -0.8 } },
      { id: 'low',   label_he: '<10%', label_en: '<10%',  weights: { story_dependency: 0.2 } },
      { id: 'mid',   label_he: '10–30%',label_en: '10–30%',weights: { story_dependency: 0.7, narrative_susceptibility: 0.6 } },
      { id: 'high',  label_he: '>30%', label_en: '>30%',  weights: { story_dependency: 1.0, narrative_susceptibility: 1.0, rule_adherence: -0.7 } },
    ],
    branches: {},
  }),
  n({
    code: 'PROBE_LEVERAGE_QUANT', stratum: 'S5', category: 'depth_probe', tier: 3,
    prompt_he: 'מה הסיכון המקסימלי לטרייד שעשית ב-30 הימים האחרונים (כ-R)?',
    prompt_en: 'What\'s the maximum per-trade risk you ran in the last 30 days (in R)?',
    options: [
      { id: 'one',  label_he: '≤1R',    label_en: '≤1R',    weights: { leverage_hubris: -0.9, rule_adherence: 0.8 } },
      { id: 'two',  label_he: '1–2R',   label_en: '1–2R',   weights: { leverage_hubris: 0.2 } },
      { id: 'four', label_he: '2–4R',   label_en: '2–4R',   weights: { leverage_hubris: 0.8, rule_adherence: -0.5 } },
      { id: 'huge', label_he: '>4R',    label_en: '>4R',    weights: { leverage_hubris: 1.0, ego_attribution: 0.7, rule_adherence: -1.0 } },
    ],
    branches: {},
  }),
];

export const ORACLE_NODES_BY_CODE: Record<string, OracleNode> = ORACLE_SEED_NODES.reduce(
  (acc, x) => { acc[x.code] = x; return acc; },
  {} as Record<string, OracleNode>,
);

export function depthProbeForDimension(dim: string): string | null {
  const map: Record<string, string> = {
    impulsivity: 'PROBE_IMPULSIVITY_QUANT',
    fomo_amplitude: 'PROBE_IMPULSIVITY_QUANT',
    plan_drift: 'PROBE_IMPULSIVITY_QUANT',
    loss_aversion: 'PROBE_LOSS_AVERSION_QUANT',
    stop_moving_tendency: 'PROBE_LOSS_AVERSION_QUANT',
    freeze_at_red: 'PROBE_LOSS_AVERSION_QUANT',
    story_dependency: 'PROBE_STORY_QUANT',
    narrative_susceptibility: 'PROBE_STORY_QUANT',
    leverage_hubris: 'PROBE_LEVERAGE_QUANT',
    ego_attribution: 'PROBE_LEVERAGE_QUANT',
  };
  return map[dim] ?? null;
}
