// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-portfolios.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-portfolios.ts
var list_portfolios_default = defineTool({
  name: "list_portfolios",
  title: "List portfolios",
  description: "List the signed-in trader's portfolios (id, name, currency, starting balance).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("portfolios").select("id, name, currency, starting_balance, is_default, sort_order").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { portfolios: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trades.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^4.6.2";

// src/lib/mcp/trades.ts
function num(value) {
  const n = typeof value === "string" ? Number(value) : typeof value === "number" ? value : null;
  return n === null || Number.isNaN(n) ? null : n;
}
function str(value) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}
function normalizeTrade(row) {
  const d = row.data ?? {};
  const pnl = num(d.pnl) ?? 0;
  const r = row.manual_r_multiple ?? num(d.manualR) ?? num(d.returnR) ?? 0;
  const rawOutcome = str(d.winLoss);
  const outcome = rawOutcome === "Win" ? "Win" : rawOutcome === "Loss" ? "Loss" : r > 0 ? "Win" : r < 0 ? "Loss" : "Breakeven";
  return {
    id: row.id,
    ref: row.trade_id,
    symbol: str(d.coin) ?? str(d.symbol),
    direction: str(d.direction),
    date: row.closed_at ?? str(d.date) ?? row.opened_at,
    entry: num(d.entry),
    exit: num(d.exit),
    stopLoss: num(d.stopLoss),
    pnl,
    rMultiple: r,
    outcome,
    notes: str(d.comments)
  };
}
function summarize(trades) {
  const total = trades.length;
  if (total === 0) {
    return { total, winRate: 0, expectancyR: 0, profitFactor: 0, netPnl: 0, netR: 0, maxDrawdown: 0, avgWinR: 0, avgLossR: 0 };
  }
  const wins = trades.filter((t) => t.outcome === "Win");
  const losses = trades.filter((t) => t.outcome === "Loss");
  const grossWin = wins.reduce((s, t) => s + Math.abs(t.pnl), 0);
  const grossLoss = losses.reduce((s, t) => s + Math.abs(t.pnl), 0);
  const netR = trades.reduce((s, t) => s + t.rMultiple, 0);
  const chronological = [...trades].sort((a, b) => (a.date ?? "").localeCompare(b.date ?? ""));
  let peak = 0;
  let equity = 0;
  let maxDrawdown = 0;
  for (const t of chronological) {
    equity += t.rMultiple;
    peak = Math.max(peak, equity);
    maxDrawdown = Math.max(maxDrawdown, peak - equity);
  }
  const round = (n) => Math.round(n * 100) / 100;
  return {
    total,
    winRate: round(wins.length / total * 100),
    expectancyR: round(netR / total),
    profitFactor: grossLoss > 0 ? round(grossWin / grossLoss) : grossWin > 0 ? Infinity : 0,
    netPnl: round(trades.reduce((s, t) => s + t.pnl, 0)),
    netR: round(netR),
    maxDrawdown: round(maxDrawdown),
    avgWinR: wins.length ? round(wins.reduce((s, t) => s + t.rMultiple, 0) / wins.length) : 0,
    avgLossR: losses.length ? round(losses.reduce((s, t) => s + t.rMultiple, 0) / losses.length) : 0
  };
}
var TRADE_COLUMNS = "id, trade_id, portfolio_id, opened_at, closed_at, manual_r_multiple, data";

// src/lib/mcp/tools/list-trades.ts
var list_trades_default = defineTool2({
  name: "list_trades",
  title: "List trades",
  description: "List the signed-in trader's most recent trades, optionally filtered by portfolio, outcome, or date range.",
  inputSchema: {
    portfolio_id: z.string().uuid().optional().describe("Only trades in this portfolio."),
    outcome: z.enum(["Win", "Loss", "Breakeven"]).optional().describe("Filter by trade outcome."),
    from: z.string().optional().describe("ISO date lower bound on the close date, e.g. 2026-01-01."),
    to: z.string().optional().describe("ISO date upper bound on the close date."),
    limit: z.number().int().min(1).max(200).default(30).describe("Maximum number of trades to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ portfolio_id, outcome, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("trades").select(TRADE_COLUMNS).order("closed_at", { ascending: false, nullsFirst: false });
    if (portfolio_id) query = query.eq("portfolio_id", portfolio_id);
    if (from) query = query.gte("closed_at", from);
    if (to) query = query.lte("closed_at", to);
    const { data, error } = await query.limit(Math.min(limit * 3, 500));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let trades = (data ?? []).map(normalizeTrade);
    if (outcome) trades = trades.filter((t) => t.outcome === outcome);
    trades = trades.slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(trades) }],
      structuredContent: { count: trades.length, trades }
    };
  }
});

// src/lib/mcp/tools/performance-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^4.6.2";
var performance_summary_default = defineTool3({
  name: "performance_summary",
  title: "Performance summary",
  description: "Compute the signed-in trader's performance stats (win rate, expectancy in R, profit factor, net P&L, max drawdown in R) plus per-symbol and per-weekday breakdowns.",
  inputSchema: {
    portfolio_id: z2.string().uuid().optional().describe("Restrict the analysis to one portfolio."),
    from: z2.string().optional().describe("ISO date lower bound on the close date."),
    to: z2.string().optional().describe("ISO date upper bound on the close date.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ portfolio_id, from, to }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("trades").select(TRADE_COLUMNS).limit(5e3);
    if (portfolio_id) query = query.eq("portfolio_id", portfolio_id);
    if (from) query = query.gte("closed_at", from);
    if (to) query = query.lte("closed_at", to);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const trades = (data ?? []).map(normalizeTrade);
    const overall = summarize(trades);
    const bucket = (key) => {
      const groups = /* @__PURE__ */ new Map();
      for (const t of trades) {
        const k = key(t);
        if (!k) continue;
        const list = groups.get(k) ?? [];
        list.push(t);
        groups.set(k, list);
      }
      return [...groups.entries()].map(([name, list]) => ({ name, ...summarize(list) })).sort((a, b) => b.netR - a.netR);
    };
    const bySymbol = bucket((t) => t.symbol);
    const byWeekday = bucket((t) => {
      if (!t.date) return null;
      const parsed = new Date(t.date);
      return Number.isNaN(parsed.getTime()) ? null : ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][parsed.getDay()];
    });
    const payload = { overall, bySymbol, byWeekday };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/trader-mind-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
var trader_mind_profile_default = defineTool4({
  name: "trader_mind_profile",
  title: "Trader Mind profile",
  description: "Return the signed-in trader's most recent Trader Mind behavioural diagnostic result (archetype and answers), if one exists.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trader_mind_sessions").select("archetype, version, payload, completed_at").order("completed_at", { ascending: false, nullsFirst: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No Trader Mind diagnostic has been completed yet." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/tools/log-day-note.ts
import { defineTool as defineTool5, ToolError } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^4.6.2";
var log_day_note_default = defineTool5({
  name: "log_day_note",
  title: "Log a journal day note",
  description: "Create or replace the signed-in trader's journal note for a specific calendar day.",
  inputSchema: {
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Calendar day in YYYY-MM-DD format."),
    note: z3.string().trim().min(1).max(4e3).describe("The note text to store for that day."),
    portfolio_id: z3.string().uuid().optional().describe("Attach the note to a specific portfolio.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, note, portfolio_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError("Could not resolve the signed-in user.");
    const supabase = supabaseForUser(ctx);
    let existing = supabase.from("day_notes").select("id").eq("date", date).limit(1);
    existing = portfolio_id ? existing.eq("portfolio_id", portfolio_id) : existing.is("portfolio_id", null);
    const { data: found, error: findError } = await existing.maybeSingle();
    if (findError) return { content: [{ type: "text", text: findError.message }], isError: true };
    const { data, error } = found ? await supabase.from("day_notes").update({ note }).eq("id", found.id).select("id, date, note").maybeSingle() : await supabase.from("day_notes").insert({ user_id: userId, date, note, portfolio_id: portfolio_id ?? null }).select("id, date, note").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved note for ${date}.` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pqezqcbbaekohzqnpmoc";
var mcp_default = defineMcp({
  name: "open-explore",
  title: "open-explore",
  version: "0.1.0",
  instructions: "Trading journal tools for ORCA Investment. Use `list_portfolios` to find a portfolio id, `list_trades` for recent trades, `performance_summary` for win rate / expectancy in R / profit factor / drawdown with per-symbol and per-weekday breakdowns, `trader_mind_profile` for the trader's behavioural diagnostic, and `log_day_note` to write a journal note. Always express edge in R-multiples, never as raw percentages, and never give financial advice.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_portfolios_default, list_trades_default, performance_summary_default, trader_mind_profile_default, log_day_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
