// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-portfolios.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_portfolios_default = defineTool({
  name: "list_portfolios",
  title: "List portfolios",
  description: "List all trading portfolios owned by the signed-in ORCA user, including currency and starting balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("portfolios").select("id,name,currency,starting_balance,is_default,created_at").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { portfolios: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trades.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trades_default = defineTool2({
  name: "list_trades",
  title: "List trades",
  description: "List the signed-in ORCA user's most recent trades, optionally filtered by portfolio. Returns id, symbol, direction, R multiple and P&L extracted from the trade payload.",
  inputSchema: {
    portfolio_id: z.string().uuid().nullable().describe("Optional portfolio UUID to filter by. Pass null for all portfolios."),
    limit: z.number().int().min(1).max(200).nullable().describe("Max rows to return (1-200). Defaults to 50 when null.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ portfolio_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("trades").select("id,portfolio_id,asset_class,opened_at,closed_at,manual_r_multiple,data").order("closed_at", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (portfolio_id) q = q.eq("portfolio_id", portfolio_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((t) => {
      const d = t.data ?? {};
      return {
        id: t.id,
        portfolio_id: t.portfolio_id,
        asset_class: t.asset_class,
        opened_at: t.opened_at,
        closed_at: t.closed_at,
        symbol: d.symbol ?? d.ticker ?? null,
        direction: d.direction ?? d.side ?? null,
        pnl: d.pnl ?? d.netPnl ?? null,
        r_multiple: t.manual_r_multiple ?? d.rMultiple ?? d.r_multiple ?? null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { trades: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-trade-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_trade_stats_default = defineTool3({
  name: "get_trade_stats",
  title: "Get trade stats",
  description: "Aggregate the signed-in user's trades into win rate, total R, average R, expectancy, and total P&L. Optionally scoped to a portfolio and a lookback window in days.",
  inputSchema: {
    portfolio_id: z2.string().uuid().nullable().describe("Optional portfolio UUID. Null = all portfolios."),
    days: z2.number().int().min(1).max(3650).nullable().describe("Lookback window in days based on closed_at. Null = all time.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ portfolio_id, days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("trades").select("manual_r_multiple,data,closed_at").not("closed_at", "is", null);
    if (portfolio_id) q = q.eq("portfolio_id", portfolio_id);
    if (days) {
      const since = new Date(Date.now() - days * 864e5).toISOString();
      q = q.gte("closed_at", since);
    }
    const { data, error } = await q.limit(5e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let wins = 0, losses = 0, rSum = 0, rCount = 0, pnlSum = 0;
    for (const t of data ?? []) {
      const d = t.data ?? {};
      const r = t.manual_r_multiple ?? d.rMultiple ?? d.r_multiple;
      const pnl = Number(d.pnl ?? d.netPnl ?? 0);
      if (Number.isFinite(pnl)) pnlSum += pnl;
      if (typeof r === "number" && Number.isFinite(r)) {
        rSum += r;
        rCount++;
        if (r > 0) wins++;
        else if (r < 0) losses++;
      } else if (Number.isFinite(pnl)) {
        if (pnl > 0) wins++;
        else if (pnl < 0) losses++;
      }
    }
    const total = wins + losses;
    const stats = {
      total_trades: data?.length ?? 0,
      wins,
      losses,
      win_rate: total ? +(wins / total * 100).toFixed(2) : 0,
      total_r: +rSum.toFixed(3),
      avg_r: rCount ? +(rSum / rCount).toFixed(3) : 0,
      expectancy_r: rCount ? +(rSum / rCount).toFixed(3) : 0,
      total_pnl: +pnlSum.toFixed(2)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/list-economic-events.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_economic_events_default = defineTool4({
  name: "list_upcoming_economic_events",
  title: "List upcoming macro events",
  description: "List upcoming macro/economic events from the ORCA economic radar, optionally filtered by impact tier and currency.",
  inputSchema: {
    days_ahead: z3.number().int().min(1).max(30).nullable().describe("Look-ahead window in days (default 7)."),
    impact: z3.enum(["low", "medium", "high"]).nullable().describe("Filter by impact tier."),
    currency: z3.string().nullable().describe("ISO currency filter e.g. USD, EUR, CNY.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ days_ahead, impact, currency }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const until = new Date(Date.now() + (days_ahead ?? 7) * 864e5).toISOString();
    let q = sb.from("economic_events").select("id,event_name,country,currency,impact,release_at,forecast,previous,actual").gte("release_at", now).lte("release_at", until).order("release_at", { ascending: true }).limit(200);
    if (impact) q = q.eq("impact", impact);
    if (currency) q = q.eq("currency", currency.toUpperCase());
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pqezqcbbaekohzqnpmoc";
var mcp_default = defineMcp({
  name: "orca-mcp",
  title: "ORCA Trading Journal",
  version: "0.1.0",
  instructions: "Tools for the ORCA trading journal. Use `list_portfolios` and `list_trades` to inspect the signed-in trader's data, `get_trade_stats` for aggregate performance (win rate, R, expectancy, P&L), and `list_upcoming_economic_events` for the macro radar.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_portfolios_default, list_trades_default, get_trade_stats_default, list_economic_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
