-- Seed Oracle Core nodes catalog (Phase 1 seed; idempotent)
INSERT INTO public.oracle_nodes (code, category, tier, prompt_he, prompt_en, options, branches, trap, trap_pair) VALUES
('IMP_01_BREAKOUT','impulsivity',1,
 'BTC פורץ התנגדות מרכזית בנפח עולה. אין לך תכנית מוקדמת לרמה הזו. מה אתה עושה ב-3 השניות הבאות?',
 'BTC breaks a key resistance on rising volume. You had no plan for this level. What do you do in the next 3 seconds?',
 '[{"id":"enter_market","label_he":"נכנס מיד ב-Market","label_en":"Enter immediately at market","weights":{"impulsivity":0.8,"plan_drift":0.6,"fomo_amplitude":0.7}},{"id":"small_probe","label_he":"נכנס בפוזיציה קטנה לבדיקה","label_en":"Enter a small probe position","weights":{"impulsivity":0.3,"rule_adherence":0.2}},{"id":"wait_retest","label_he":"מחכה לרי-טסט","label_en":"Wait for a retest","weights":{"impulsivity":-0.5,"rule_adherence":0.6,"decision_fatigue_slope":0.1}},{"id":"skip_setup","label_he":"לא נכנס — אין תכנית","label_en":"Skip — no plan","weights":{"impulsivity":-0.8,"rule_adherence":0.9,"plan_drift":-0.7}}]'::jsonb,
 '{"enter_market":"LOSS_01_IMMEDIATE_RED","small_probe":"LOSS_01_IMMEDIATE_RED","wait_retest":"NAR_01_STORY","skip_setup":"NAR_01_STORY","*":"NAR_01_STORY"}'::jsonb, false, NULL),
('LOSS_01_IMMEDIATE_RED','loss_aversion',1,
 'דקה אחרי הכניסה אתה ב-0.7R הפסד. הסטופ עוד לא נגוע. גופך מגיב לפני הראש. מה הצעד?',
 'A minute after entry you are at -0.7R. Stop is not touched. Your body reacts before your mind. What do you do?',
 '[{"id":"tighten_stop","label_he":"מקרב סטופ כדי להגן","label_en":"Tighten stop to protect","weights":{"loss_aversion":0.8,"stop_moving_tendency":0.9,"freeze_at_red":0.3}},{"id":"add_average","label_he":"מוסיף — אני צודק","label_en":"Add to position — I am right","weights":{"loss_aversion":0.4,"impulsivity":0.6,"win_attribution_self":0.7}},{"id":"hold_plan","label_he":"נשאר עם התכנית, יושב על הידיים","label_en":"Stick to plan, sit on hands","weights":{"loss_aversion":-0.6,"rule_adherence":0.9,"drawdown_pain_curve":-0.4}},{"id":"exit_early","label_he":"יוצא עכשיו, להפסיק את הכאב","label_en":"Exit now to stop the pain","weights":{"loss_aversion":0.9,"freeze_at_red":0.7,"rule_adherence":-0.6}}]'::jsonb,
 '{"*":"EGO_01_BLAME"}'::jsonb, false, NULL),
('NAR_01_STORY','narrative_quant',1,
 'חבר שולח לך טוויט של אנליסט מפורסם: BTC ל-200K עד סוף הרבעון. איזו תגובה הכי מדויקת?',
 'A friend forwards a tweet from a famous analyst: BTC to 200K by quarter end. Which response is most accurate to you?',
 '[{"id":"believe_act","label_he":"מגדיל אקספוזר על בסיס זה","label_en":"Increase exposure based on this","weights":{"story_dependency":0.9,"news_anchoring":0.7,"leverage_hubris":0.5}},{"id":"verify_data","label_he":"בודק את הדאטה לבד לפני כל פעולה","label_en":"Verify the data myself first","weights":{"story_dependency":-0.7,"chart_pattern_overfit":0.2,"rule_adherence":0.4}},{"id":"ignore","label_he":"מתעלם — לא רלוונטי לתכנית שלי","label_en":"Ignore — irrelevant to my plan","weights":{"story_dependency":-0.9,"plan_drift":-0.6}},{"id":"fade","label_he":"מנגד — אם זה ויראלי, השוק כבר תמחר","label_en":"Fade — if it is viral, market already priced it","weights":{"story_dependency":-0.4,"news_anchoring":-0.5,"win_attribution_self":0.3}}]'::jsonb,
 '{"*":"RISK_01_MISMATCH"}'::jsonb, false, NULL),
('RISK_01_MISMATCH','risk_mismatch',1,
 'אמרת שאתה סוחר ב-1% סיכון. הטרייד הבא הוא סטאפ A+. כמה אתה באמת מסכן?',
 'You said you risk 1% per trade. The next setup is A+ conviction. How much do you actually risk?',
 '[{"id":"one","label_he":"בדיוק 1%","label_en":"Exactly 1%","weights":{"rule_adherence":0.9,"self_reported_R_vs_chosen_R":-0.8}},{"id":"one_five","label_he":"1.5% — סטאפ חזק יותר","label_en":"1.5% — stronger setup","weights":{"rule_adherence":-0.3,"self_reported_R_vs_chosen_R":0.4,"leverage_hubris":0.3}},{"id":"two_plus","label_he":"2-3% — אני בטוח","label_en":"2-3% — I am sure","weights":{"rule_adherence":-0.8,"leverage_hubris":0.9,"self_reported_R_vs_chosen_R":0.9}},{"id":"half","label_he":"פחות — אני מפחד","label_en":"Less — I am scared","weights":{"loss_aversion":0.7,"freeze_at_red":0.4}}]'::jsonb,
 '{"*":"IMP_02_TRAP"}'::jsonb, false, NULL),
('IMP_02_TRAP','impulsivity',2,
 'תרחיש: זיהית סטאפ מושלם לפי המערכת שלך, אבל הוא קופץ 1.2% לפני שאתה לוחץ שלח. מה אתה עושה?',
 'Scenario: you spot a perfect setup by your system, but it gaps 1.2% before you click submit. What do you do?',
 '[{"id":"chase","label_he":"רודף — לא רוצה לפספס","label_en":"Chase — don''t want to miss","weights":{"impulsivity":0.9,"fomo_amplitude":0.9}},{"id":"reduce","label_he":"נכנס בגודל קטן יותר","label_en":"Enter with reduced size","weights":{"impulsivity":0.2,"rule_adherence":0.4}},{"id":"pass","label_he":"מוותר — הסטאפ נפגע","label_en":"Pass — setup invalidated","weights":{"impulsivity":-0.9,"rule_adherence":0.9,"plan_drift":-0.8}}]'::jsonb,
 '{"*":"EGO_01_BLAME"}'::jsonb, true, 'IMP_01_BREAKOUT'),
('EGO_01_BLAME','ego',2,
 'הפסדת 3 טריידים ברצף. השבוע סגרת -4R. מה הכי קרוב לאמת שלך הפנימית?',
 'You lost 3 trades in a row. The week closed at -4R. What is closest to your inner truth?',
 '[{"id":"market_fault","label_he":"השוק לא הגיוני השבוע","label_en":"The market made no sense this week","weights":{"win_attribution_self":0.6,"loss_attribution_external":0.9,"rule_adherence":-0.3}},{"id":"me_fault","label_he":"אני סטיתי מהמערכת","label_en":"I drifted from my system","weights":{"loss_attribution_external":-0.8,"plan_drift":0.6,"rule_adherence":0.5}},{"id":"mixed","label_he":"גם וגם — וזה בסדר","label_en":"Both — and that is ok","weights":{"loss_attribution_external":-0.2,"decision_fatigue_slope":0.3}},{"id":"no_loss","label_he":"לא נסגרתי באמת — עוד אחזיר","label_en":"I have not really lost — I will get it back","weights":{"loss_attribution_external":0.9,"win_attribution_self":0.9,"impulsivity":0.4,"revenge_trade_propensity":0.9}}]'::jsonb,
 '{}'::jsonb, false, NULL),
('PROBE_IMPULSIVITY_QUANT','depth_probe',3,
 'בכמה אחוזים מהטריידים שלך ב-30 הימים האחרונים נכנסת בלי תכנית כתובה מראש?',
 'In what % of your trades over the last 30 days did you enter without a written plan?',
 '[{"id":"lt10","label_he":"פחות מ-10%","label_en":"Less than 10%","weights":{"impulsivity":-0.8,"rule_adherence":0.7}},{"id":"p10_30","label_he":"10-30%","label_en":"10-30%","weights":{"impulsivity":0.3,"rule_adherence":0.1}},{"id":"p30_60","label_he":"30-60%","label_en":"30-60%","weights":{"impulsivity":0.7,"plan_drift":0.6}},{"id":"gt60","label_he":"מעל 60%","label_en":"Above 60%","weights":{"impulsivity":1.0,"plan_drift":0.9,"rule_adherence":-0.9}}]'::jsonb,
 '{}'::jsonb, false, NULL),
('PROBE_LOSS_AVERSION_QUANT','depth_probe',3,
 'נתון: מתוך 100 הטריידים האחרונים, באיזה אחוז הזזת את הסטופ אחורה?',
 'Of your last 100 trades, in what % did you move your stop further away?',
 '[{"id":"never","label_he":"0%","label_en":"0%","weights":{"stop_moving_tendency":-1.0,"rule_adherence":0.9}},{"id":"few","label_he":"מתחת 10%","label_en":"Under 10%","weights":{"stop_moving_tendency":0.2}},{"id":"some","label_he":"10-30%","label_en":"10-30%","weights":{"stop_moving_tendency":0.7,"loss_aversion":0.6}},{"id":"often","label_he":"מעל 30%","label_en":"Above 30%","weights":{"stop_moving_tendency":1.0,"loss_aversion":0.9,"rule_adherence":-0.8}}]'::jsonb,
 '{}'::jsonb, false, NULL)
ON CONFLICT (code) DO UPDATE SET
  category = EXCLUDED.category, tier = EXCLUDED.tier,
  prompt_he = EXCLUDED.prompt_he, prompt_en = EXCLUDED.prompt_en,
  options = EXCLUDED.options, branches = EXCLUDED.branches,
  trap = EXCLUDED.trap, trap_pair = EXCLUDED.trap_pair,
  updated_at = now();

-- Ensure code is unique for upserts
CREATE UNIQUE INDEX IF NOT EXISTS oracle_nodes_code_unique ON public.oracle_nodes(code);